{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.19+26.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.19+26.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.19+26.2-SNAPSHOT.jar",
          "size": 55565,
          "sha512": "55097d3dde371a2a83e6742c298b7e47b337b752cefd4c9d02edf1d670a4d545c0e66d1ae21a0bdcb9c82e8f0b4f8c7af898b273a01c905c3d7693f2fa915ab9",
          "sha256": "29074a35fb38f40b54939e99ddac15e69f46844ecf15841062df4234263022be",
          "sha1": "715128aa01b51a3b72930b130fcc6870e149917d",
          "md5": "83078028f11d0055ffec49c5dfaa384c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.19+26.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.19+26.2-SNAPSHOT.jar",
          "size": 55565,
          "sha512": "55097d3dde371a2a83e6742c298b7e47b337b752cefd4c9d02edf1d670a4d545c0e66d1ae21a0bdcb9c82e8f0b4f8c7af898b273a01c905c3d7693f2fa915ab9",
          "sha256": "29074a35fb38f40b54939e99ddac15e69f46844ecf15841062df4234263022be",
          "sha1": "715128aa01b51a3b72930b130fcc6870e149917d",
          "md5": "83078028f11d0055ffec49c5dfaa384c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.19+26.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.19+26.2-SNAPSHOT-sources.jar",
          "size": 43188,
          "sha512": "7b4f7338ba72211c68469f1aa7e8d591a756f7c92e70179413e929d197c69cf967f257adf5907d897ad5f6bd6cd34b1e40f04a18e4b8c2137cc78151eb4914ee",
          "sha256": "97935cedf6865782f58d927210ff7ef6afd6073c60ab8539f17a35b6eab8656c",
          "sha1": "2740d3a77c2c9d726b50a3232f8121abbf7e943b",
          "md5": "fdd99bc7d711d41cef0fa3bce80e3324"
        }
      ]
    }
  ]
}
