{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.15+26.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.15+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.15+26.1.2-SNAPSHOT.jar",
          "size": 55566,
          "sha512": "d4eaa340dc85bc629db6d5e35722771893acfa5ad341a52f22ca0853e9d0f0bdb449bb4540473a708ed3fd4789d0dc360a7712eecd8deb902c8cc6c0902d0e97",
          "sha256": "9c64f29d825d8b313669463e4db046dd64b072e43833af27aca726c18e1b6e09",
          "sha1": "e9dec521311605eead5b4992ffa9948b00390c17",
          "md5": "dc1b93ef93de3af9cdde06969d669805"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.15+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.15+26.1.2-SNAPSHOT.jar",
          "size": 55566,
          "sha512": "d4eaa340dc85bc629db6d5e35722771893acfa5ad341a52f22ca0853e9d0f0bdb449bb4540473a708ed3fd4789d0dc360a7712eecd8deb902c8cc6c0902d0e97",
          "sha256": "9c64f29d825d8b313669463e4db046dd64b072e43833af27aca726c18e1b6e09",
          "sha1": "e9dec521311605eead5b4992ffa9948b00390c17",
          "md5": "dc1b93ef93de3af9cdde06969d669805"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.15+26.1.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.15+26.1.2-SNAPSHOT-sources.jar",
          "size": 43190,
          "sha512": "06dc7f90690a79d77c3017ea67d792f2759cc523fe8d73c4113e855a42a7fbd8796fb576ec465b2f09a482159dc7a06d666c7dda8a4605f02a681a0d8cad59c2",
          "sha256": "f323fc1893a4c6536f97ce5225580730d3d88182a821efeb380d9d9c96a38325",
          "sha1": "5c23b95438b5379056c88835ec14f3bb67bbd431",
          "md5": "9bf806e2615e74a2ff04c9f4ca1925d6"
        }
      ]
    }
  ]
}
