{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.1+26.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.1+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.1+26.1.2-SNAPSHOT.jar",
          "size": 20097,
          "sha512": "0547a39074285ed6efa68a4b1b7b50920d769486d105398c007686b914d104237bbee536fbd33b0187ff585fa93c5b0372ae3d75eb372e43b8013af3acd72cdc",
          "sha256": "251f59c2e6aed89559dba954d8e0d6e2f08dd22a9e5651764c799ab36b8f2f69",
          "sha1": "dd29ec71cb33833556d56098318cfddfb6b5d576",
          "md5": "ccb3d98e9b89f217b8872b2f2355e14f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.1+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.1+26.1.2-SNAPSHOT.jar",
          "size": 20097,
          "sha512": "0547a39074285ed6efa68a4b1b7b50920d769486d105398c007686b914d104237bbee536fbd33b0187ff585fa93c5b0372ae3d75eb372e43b8013af3acd72cdc",
          "sha256": "251f59c2e6aed89559dba954d8e0d6e2f08dd22a9e5651764c799ab36b8f2f69",
          "sha1": "dd29ec71cb33833556d56098318cfddfb6b5d576",
          "md5": "ccb3d98e9b89f217b8872b2f2355e14f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.1+26.1.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.1+26.1.2-SNAPSHOT-sources.jar",
          "size": 11437,
          "sha512": "233a636dda98ba30256e366f2d469a77069e3967e11f4244bbd561ad6f1c88b38e17bde8b56b27b991f1793b99813f500e52fb9c0528c35957b3128cc0d08830",
          "sha256": "94b84fd0486027755c81c4141b65d6fac9a4aaff51a9f5a30696f67dd363b2fc",
          "sha1": "3e3c75688dfe4dd2923344b5d960c712f10b976c",
          "md5": "2f4a800329c6554b984b594e4c876c40"
        }
      ]
    }
  ]
}
