{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.16+26.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.16+26.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.16+26.2-SNAPSHOT.jar",
          "size": 55566,
          "sha512": "69511505a45b7acc030a4e209bad739be0ceac57ef71f267c4e07df8230e91af5ddc02e6114b85ea8ed9d667047644d6d1d9237c63865db18ecf797c1404e5d4",
          "sha256": "1681d73e599e235d49e39c281f007d8159a72e9887133699bf77f0cde7d7b4ad",
          "sha1": "0f441ab255afa82ea8b56cbdffbb7c74a3ddcc36",
          "md5": "f26c8d16f3d2b9ed6d670e3eccf96332"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.16+26.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.16+26.2-SNAPSHOT.jar",
          "size": 55566,
          "sha512": "69511505a45b7acc030a4e209bad739be0ceac57ef71f267c4e07df8230e91af5ddc02e6114b85ea8ed9d667047644d6d1d9237c63865db18ecf797c1404e5d4",
          "sha256": "1681d73e599e235d49e39c281f007d8159a72e9887133699bf77f0cde7d7b4ad",
          "sha1": "0f441ab255afa82ea8b56cbdffbb7c74a3ddcc36",
          "md5": "f26c8d16f3d2b9ed6d670e3eccf96332"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.16+26.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.16+26.2-SNAPSHOT-sources.jar",
          "size": 43188,
          "sha512": "7b4f7338ba72211c68469f1aa7e8d591a756f7c92e70179413e929d197c69cf967f257adf5907d897ad5f6bd6cd34b1e40f04a18e4b8c2137cc78151eb4914ee",
          "sha256": "97935cedf6865782f58d927210ff7ef6afd6073c60ab8539f17a35b6eab8656c",
          "sha1": "2740d3a77c2c9d726b50a3232f8121abbf7e943b",
          "md5": "fdd99bc7d711d41cef0fa3bce80e3324"
        }
      ]
    }
  ]
}
