{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.18+26.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.18+26.1.2.jar",
          "url": "vaw-api-1.0.18+26.1.2.jar",
          "size": 55558,
          "sha512": "1b604ae6de93df8ad44ccb7080c3782411c3a547c162da62dca3e3203936f35d7d592a703da49cf9e89e6f9bb85e269d66143f419256a051c7fde1c8feb1a951",
          "sha256": "ca9919b42d25a1b3801341aa26037a86f89eba86f0b8c01cf32929378a91bed9",
          "sha1": "0a88efd1534795fb550d37e5232819a16d4e011c",
          "md5": "dcefb8a361117d6ac465ab15abc2373b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.18+26.1.2.jar",
          "url": "vaw-api-1.0.18+26.1.2.jar",
          "size": 55558,
          "sha512": "1b604ae6de93df8ad44ccb7080c3782411c3a547c162da62dca3e3203936f35d7d592a703da49cf9e89e6f9bb85e269d66143f419256a051c7fde1c8feb1a951",
          "sha256": "ca9919b42d25a1b3801341aa26037a86f89eba86f0b8c01cf32929378a91bed9",
          "sha1": "0a88efd1534795fb550d37e5232819a16d4e011c",
          "md5": "dcefb8a361117d6ac465ab15abc2373b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.18+26.1.2-sources.jar",
          "url": "vaw-api-1.0.18+26.1.2-sources.jar",
          "size": 43192,
          "sha512": "d084df9523c2281a50a054db05c8139cfe8f13badfb2afefb73259d08849ad192c4534b9de8a6a20187f269364f6a7b379d659d69d2a542d34bc589a4ab495bd",
          "sha256": "4c886a22b960329fb06a3798c528dff3aab85b0f5cb4c5bf4d1ed70bc77dba4d",
          "sha1": "35934e0f16c10c4b798669905f22ea32d352d59f",
          "md5": "a6202748b342579805cc5a9e48b62f78"
        }
      ]
    }
  ]
}
