{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.16+26.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.16+26.3.jar",
          "url": "vaw-api-1.0.16+26.3.jar",
          "size": 55555,
          "sha512": "8fa1e31bb45d4b84bdd525945f0a3c72f4f69edcf5c70800a65ce4b6c8ca75f3055ae7d4a4180b43cfd122362d67e283ae47fd6f8a680addb0bc0268841bd85c",
          "sha256": "e3b84d025c16eea2f01fa46ca24971e49a139b337e32ff7fd2efc69de8267bdd",
          "sha1": "1818f405b1567e39cad9851f35d5f11672b484a9",
          "md5": "30dc73ca718d270b1a3bbdf1b6957487"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.16+26.3.jar",
          "url": "vaw-api-1.0.16+26.3.jar",
          "size": 55555,
          "sha512": "8fa1e31bb45d4b84bdd525945f0a3c72f4f69edcf5c70800a65ce4b6c8ca75f3055ae7d4a4180b43cfd122362d67e283ae47fd6f8a680addb0bc0268841bd85c",
          "sha256": "e3b84d025c16eea2f01fa46ca24971e49a139b337e32ff7fd2efc69de8267bdd",
          "sha1": "1818f405b1567e39cad9851f35d5f11672b484a9",
          "md5": "30dc73ca718d270b1a3bbdf1b6957487"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.16+26.3-sources.jar",
          "url": "vaw-api-1.0.16+26.3-sources.jar",
          "size": 43188,
          "sha512": "8fea454ca4bb5f82219404a30fd162b64bd28f69e30727939b7e1cd64eec06df0bea476dce11a826446f68cb80d37a2ac508d753547bc3929d967e5ce386221e",
          "sha256": "33ed5db5c68facd0b839010d56e257866903b1a5696cf004393d100322b58370",
          "sha1": "d518e2a88e91c9bc457f28c6ae572060d2336d14",
          "md5": "2ad4b2d2a69cf634fdc5737dbe870a4c"
        }
      ]
    }
  ]
}
