{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.9.13+26.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.13+26.1.2.jar",
          "url": "vaw-api-0.9.13+26.1.2.jar",
          "size": 16362,
          "sha512": "3348472e3c35f3b579273b270e7f5720bf1b7ea3dab7b3c9feb4471ba8e1dd4bca4ccd8db60f46c4caad63f89e6c803b4c536986cffc7021270cf416684fc591",
          "sha256": "a419d77ef3eb048e84ef767a8bd38c1443f6e2253e61b5cf47310590d56dff97",
          "sha1": "93634f24799071e021f93e00762b1a1c8b5a546d",
          "md5": "5629adf43ca2891381f8173d019b7792"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.13+26.1.2.jar",
          "url": "vaw-api-0.9.13+26.1.2.jar",
          "size": 16362,
          "sha512": "3348472e3c35f3b579273b270e7f5720bf1b7ea3dab7b3c9feb4471ba8e1dd4bca4ccd8db60f46c4caad63f89e6c803b4c536986cffc7021270cf416684fc591",
          "sha256": "a419d77ef3eb048e84ef767a8bd38c1443f6e2253e61b5cf47310590d56dff97",
          "sha1": "93634f24799071e021f93e00762b1a1c8b5a546d",
          "md5": "5629adf43ca2891381f8173d019b7792"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.9.13+26.1.2-sources.jar",
          "url": "vaw-api-0.9.13+26.1.2-sources.jar",
          "size": 8059,
          "sha512": "6f5ddc94fa6904c87ff7b96c7660cd8ae873444718aca45c92f60d40e79e7221668601fd0980d89aca4835377fce0140482f623177a27d699c48d07e36fab27b",
          "sha256": "e7702817f7f075441f0dd29886a097308c895f64d22a0551a092c602639a3bf9",
          "sha1": "2e099123f34ab499ad7bf0d373ac727da6655845",
          "md5": "b4d8248deb7da31627f670f7b4bd75b2"
        }
      ]
    }
  ]
}
