{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.9.3+26.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.3+26.3-SNAPSHOT.jar",
          "url": "vaw-api-0.9.3+26.3-SNAPSHOT.jar",
          "size": 16226,
          "sha512": "48e42d5b181bc6fc170b188089d7baddf78518c204bedfbda4199acd5f9feb307a7a6a4f5555ef7abcb172d84edb1bb09623ad0c55a3e0f8cce52e3382e73383",
          "sha256": "b6f3a3e43311f0c266da16b0d02d262609c3b77d08a68df0894eceaf0c18b1ad",
          "sha1": "d4a2b84907a0263e83a1c70e4658b683a5dd35cc",
          "md5": "7251cef936370c558bf00387ac292e5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.3+26.3-SNAPSHOT.jar",
          "url": "vaw-api-0.9.3+26.3-SNAPSHOT.jar",
          "size": 16226,
          "sha512": "48e42d5b181bc6fc170b188089d7baddf78518c204bedfbda4199acd5f9feb307a7a6a4f5555ef7abcb172d84edb1bb09623ad0c55a3e0f8cce52e3382e73383",
          "sha256": "b6f3a3e43311f0c266da16b0d02d262609c3b77d08a68df0894eceaf0c18b1ad",
          "sha1": "d4a2b84907a0263e83a1c70e4658b683a5dd35cc",
          "md5": "7251cef936370c558bf00387ac292e5d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.9.3+26.3-SNAPSHOT-sources.jar",
          "url": "vaw-api-0.9.3+26.3-SNAPSHOT-sources.jar",
          "size": 7861,
          "sha512": "496306528cb7d459ae5c54df4fab63c50315dfab8df3f96a43f6bbf615621fca5ddad4b2ea44d0bf56378eb5393a132b19c9d8ceaae4c6018b559d7fd2ede201",
          "sha256": "ff6a879b8049504bd1ba1eb99e01c926eea3ef9c5add0ac2a6781cd658ebdfc6",
          "sha1": "3d289c41b1af11e269338cadbe310e255184f63e",
          "md5": "ac0dea5b3484c057b2ac12457bd15101"
        }
      ]
    }
  ]
}
