{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.9.14+26.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.14+26.2-SNAPSHOT.jar",
          "url": "vaw-api-0.9.14+26.2-SNAPSHOT.jar",
          "size": 18476,
          "sha512": "e66e51fcaa39d2fcc20e4b92bd67c226385def20f6af72d4785c8f25451f053224620c75b4becd38c3ec5bb735f281e7cd79051b83a4fccb129e0b704b446456",
          "sha256": "41fc3e8419ca6dcaa434b35b2d5dfd4d79b6c56b956c3145632b82628c9383d5",
          "sha1": "328eac467214edd6980a3877d7eaa214a938f994",
          "md5": "946d9ecd98f11d7e558fafc3a3b95485"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.14+26.2-SNAPSHOT.jar",
          "url": "vaw-api-0.9.14+26.2-SNAPSHOT.jar",
          "size": 18476,
          "sha512": "e66e51fcaa39d2fcc20e4b92bd67c226385def20f6af72d4785c8f25451f053224620c75b4becd38c3ec5bb735f281e7cd79051b83a4fccb129e0b704b446456",
          "sha256": "41fc3e8419ca6dcaa434b35b2d5dfd4d79b6c56b956c3145632b82628c9383d5",
          "sha1": "328eac467214edd6980a3877d7eaa214a938f994",
          "md5": "946d9ecd98f11d7e558fafc3a3b95485"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.9.14+26.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-0.9.14+26.2-SNAPSHOT-sources.jar",
          "size": 10005,
          "sha512": "eaa87e2a945fa6bfbc83d3e477f65484cbfc78ebee8488776f904dd061e522dcb310545748e994941d1e5f567769ea108300a96eedfc883ed96489b7829d2e44",
          "sha256": "03115d5d82aec252c0e494711bf5e0e712509443e039edfeeea1ab1e06ff55b7",
          "sha1": "4d9da97d1e71ee65bf0abb3ef53eca1941294393",
          "md5": "a6bea7faaf026803122c2b437975debb"
        }
      ]
    }
  ]
}
