{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.7+26.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.7+26.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.7+26.2-SNAPSHOT.jar",
          "size": 25808,
          "sha512": "be44a0564dacd006b3489db475b045bed73018a0c13f5af7a31904bd68653001a6f66e081061c0342b5f75f8f3948a9fa4c0f756535029bd745de03abce95dcc",
          "sha256": "ee8b79684050896b87ab3b8fdfa756e8be4d60af766436c91ec657c27247be24",
          "sha1": "aca5fb7c632666e4bd0519ff06fadcd8ed37cc91",
          "md5": "a60a82c2d6b16e8fe7cdfcacea890888"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.7+26.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.7+26.2-SNAPSHOT.jar",
          "size": 25808,
          "sha512": "be44a0564dacd006b3489db475b045bed73018a0c13f5af7a31904bd68653001a6f66e081061c0342b5f75f8f3948a9fa4c0f756535029bd745de03abce95dcc",
          "sha256": "ee8b79684050896b87ab3b8fdfa756e8be4d60af766436c91ec657c27247be24",
          "sha1": "aca5fb7c632666e4bd0519ff06fadcd8ed37cc91",
          "md5": "a60a82c2d6b16e8fe7cdfcacea890888"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.7+26.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.7+26.2-SNAPSHOT-sources.jar",
          "size": 14403,
          "sha512": "62a5c3a3e250015d41f733ad0ac5adddbf7a8304a8da1c407b9a1843182e52f8d206cda579903eeee4d92cedcf406ee7a1107567d8a12ef8bc908b7cee515158",
          "sha256": "9e2fffe786a57e658389ebff5808b1a0d1fb3f7c4ad74aca31e05b73d0971268",
          "sha1": "d2dacb7c5f9126746efa2057b9fccf4fae908f01",
          "md5": "61c35276c94dc5951d6f10673e68f73e"
        }
      ]
    }
  ]
}
