{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.19+26.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.19+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.19+26.1.2-SNAPSHOT.jar",
          "size": 55568,
          "sha512": "55507dbb4235a4fb85a896ac5d141b4cd8e2cac2a4e84df701a8dda7cc86f9a67f34c892755af2afd38c71e3231aa35e51083dc558dde7287eabaf6b08208c64",
          "sha256": "18229f9bd8d638940389ca6f50b02b36a519f2f3982493326c7a1ac68a90cb15",
          "sha1": "d964856476019e696ce5149eb0be562bda62e3ec",
          "md5": "bf40cb7fcf1c44983ba372af3f22f391"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.19+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.19+26.1.2-SNAPSHOT.jar",
          "size": 55568,
          "sha512": "55507dbb4235a4fb85a896ac5d141b4cd8e2cac2a4e84df701a8dda7cc86f9a67f34c892755af2afd38c71e3231aa35e51083dc558dde7287eabaf6b08208c64",
          "sha256": "18229f9bd8d638940389ca6f50b02b36a519f2f3982493326c7a1ac68a90cb15",
          "sha1": "d964856476019e696ce5149eb0be562bda62e3ec",
          "md5": "bf40cb7fcf1c44983ba372af3f22f391"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.19+26.1.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.19+26.1.2-SNAPSHOT-sources.jar",
          "size": 43192,
          "sha512": "d084df9523c2281a50a054db05c8139cfe8f13badfb2afefb73259d08849ad192c4534b9de8a6a20187f269364f6a7b379d659d69d2a542d34bc589a4ab495bd",
          "sha256": "4c886a22b960329fb06a3798c528dff3aab85b0f5cb4c5bf4d1ed70bc77dba4d",
          "sha1": "35934e0f16c10c4b798669905f22ea32d352d59f",
          "md5": "a6202748b342579805cc5a9e48b62f78"
        }
      ]
    }
  ]
}
