{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.0+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.0+26.2.jar",
          "url": "vaw-api-1.0.0+26.2.jar",
          "size": 20086,
          "sha512": "1f9ac83876041255bb9160dd518efa88344328ccbc0a3768bc7f2f478e356a7bc08a45d3c98b83b41fc7e556c3d88d27b34dd87ee669b82d1bc47778957c4a2c",
          "sha256": "ae08db061c8bef3e029eb69cb7d5ee6353faf5e798112dcdf2f765ca6eb2ac7f",
          "sha1": "dbfcab471aef69305259a53658b068bd1cd01035",
          "md5": "b0a973ce9a3244e7db453d955f9890a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.0+26.2.jar",
          "url": "vaw-api-1.0.0+26.2.jar",
          "size": 20086,
          "sha512": "1f9ac83876041255bb9160dd518efa88344328ccbc0a3768bc7f2f478e356a7bc08a45d3c98b83b41fc7e556c3d88d27b34dd87ee669b82d1bc47778957c4a2c",
          "sha256": "ae08db061c8bef3e029eb69cb7d5ee6353faf5e798112dcdf2f765ca6eb2ac7f",
          "sha1": "dbfcab471aef69305259a53658b068bd1cd01035",
          "md5": "b0a973ce9a3244e7db453d955f9890a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.0+26.2-sources.jar",
          "url": "vaw-api-1.0.0+26.2-sources.jar",
          "size": 11433,
          "sha512": "25a52f98d277fbec984444d35226ae5730b082669de4e4341017b3eb03d6a175b0210a491339aade2c2f03981e47f230b2ed7669dd5f311b3cc8939f5f8abd71",
          "sha256": "45c62fc25d41f84b66f83522f33f70601a9eede86a8a85fab33c4b18c5ef25c9",
          "sha1": "0b8a869baa3fa7c9bfabb3c13574d8cb71b0abc4",
          "md5": "90d0c980eab2bfcc426c53298b492d45"
        }
      ]
    }
  ]
}
