{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.11+26.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.11+26.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.11+26.2-SNAPSHOT.jar",
          "size": 26945,
          "sha512": "8376ab03af4eafff6ea1bcb053a8970dbb748f86fc6354f6630a2012f2794b77bf4b8c8c985d32f4dae6d0f4373e27d4fe3616abac4026fe1e23d33a2beb1ac1",
          "sha256": "2b4b75f32fd3dff8cf9e831ca9ca081ab4d7ad6b7445a266a58d53060b1ee2f1",
          "sha1": "0db3e8c0ccccf5b77c66411894a5eb80b20d9568",
          "md5": "5df83499e79c4779a766d61ee30bd5c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.11+26.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.11+26.2-SNAPSHOT.jar",
          "size": 26945,
          "sha512": "8376ab03af4eafff6ea1bcb053a8970dbb748f86fc6354f6630a2012f2794b77bf4b8c8c985d32f4dae6d0f4373e27d4fe3616abac4026fe1e23d33a2beb1ac1",
          "sha256": "2b4b75f32fd3dff8cf9e831ca9ca081ab4d7ad6b7445a266a58d53060b1ee2f1",
          "sha1": "0db3e8c0ccccf5b77c66411894a5eb80b20d9568",
          "md5": "5df83499e79c4779a766d61ee30bd5c4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.11+26.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.11+26.2-SNAPSHOT-sources.jar",
          "size": 14615,
          "sha512": "672a54df014af689d3370ad647ffc802dfca614fb8f4b66a2567dec076d97bfdf2d36102d3b7d82b452f88804f5f76f547323768b5ffe229bcf476074ffaccb8",
          "sha256": "85f7da72e1b90b56676092dd1a1985741dd547944cd2cb56f1f265428f396c3a",
          "sha1": "b283e2e049cdd100e42b041c6d7a5b2b3bd27e4a",
          "md5": "3504a1b08060783a4cc98c70b8e575b6"
        }
      ]
    }
  ]
}
