{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.14+26.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.14+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.14+26.1.2-SNAPSHOT.jar",
          "size": 55565,
          "sha512": "eebbf82731051b020d400d7acc4fd0c760c4c18acd49367d0b4cedba24d0ad72a056077c3976ed1bcd1208bb8dd082cce506d25efd2588c55eb4910065a2ec90",
          "sha256": "3e2b18234a49fb76d6cc8018cf5c2ab0809c643282fa6f5bc91deec335b4a7c5",
          "sha1": "884edcf5238f2646bdaa18615ba7095580727e5f",
          "md5": "6121a9472c867376c7e4911742dfe397"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.14+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.14+26.1.2-SNAPSHOT.jar",
          "size": 55565,
          "sha512": "eebbf82731051b020d400d7acc4fd0c760c4c18acd49367d0b4cedba24d0ad72a056077c3976ed1bcd1208bb8dd082cce506d25efd2588c55eb4910065a2ec90",
          "sha256": "3e2b18234a49fb76d6cc8018cf5c2ab0809c643282fa6f5bc91deec335b4a7c5",
          "sha1": "884edcf5238f2646bdaa18615ba7095580727e5f",
          "md5": "6121a9472c867376c7e4911742dfe397"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.14+26.1.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.14+26.1.2-SNAPSHOT-sources.jar",
          "size": 43190,
          "sha512": "06dc7f90690a79d77c3017ea67d792f2759cc523fe8d73c4113e855a42a7fbd8796fb576ec465b2f09a482159dc7a06d666c7dda8a4605f02a681a0d8cad59c2",
          "sha256": "f323fc1893a4c6536f97ce5225580730d3d88182a821efeb380d9d9c96a38325",
          "sha1": "5c23b95438b5379056c88835ec14f3bb67bbd431",
          "md5": "9bf806e2615e74a2ff04c9f4ca1925d6"
        }
      ]
    }
  ]
}
