{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.9.10+26.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.10+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-0.9.10+26.1.2-SNAPSHOT.jar",
          "size": 16229,
          "sha512": "da7eedc6e65908756220b68b0b718c4c4b9a8c31cfa559508a740f49e9d40ee7bfebe754778242f4e4d390fd6f07df3ab7bba28df27f567b7b48182126660cbb",
          "sha256": "3dd0ae7b07df81e872ba4e8b4ae325969d0a864824e29fb763b5431583ac59f5",
          "sha1": "d5f462a405cd770a5e03b263f2c0fb7c2899511f",
          "md5": "aab98e6af06c3105494f737b1cd59627"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.10+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-0.9.10+26.1.2-SNAPSHOT.jar",
          "size": 16229,
          "sha512": "da7eedc6e65908756220b68b0b718c4c4b9a8c31cfa559508a740f49e9d40ee7bfebe754778242f4e4d390fd6f07df3ab7bba28df27f567b7b48182126660cbb",
          "sha256": "3dd0ae7b07df81e872ba4e8b4ae325969d0a864824e29fb763b5431583ac59f5",
          "sha1": "d5f462a405cd770a5e03b263f2c0fb7c2899511f",
          "md5": "aab98e6af06c3105494f737b1cd59627"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.9.10+26.1.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-0.9.10+26.1.2-SNAPSHOT-sources.jar",
          "size": 7865,
          "sha512": "f9f2e96b22aa2b168bc58ed0c180c7a8d8a7debb268e26dd13598da884ffb2cdc9be7e21e675242453511208005b95113116504f085e105e78001462f9ffbf38",
          "sha256": "87376adf52ffd800d1a080b6e2b4aab8ffee877c969f46878a0ac383385ac1d6",
          "sha1": "fd697b7665401aae022719cf200b2f5e13a6fe27",
          "md5": "78f230fd0d00c7862de06db13fedc33f"
        }
      ]
    }
  ]
}
