{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.5+26.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.5+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.5+26.1.2-SNAPSHOT.jar",
          "size": 25810,
          "sha512": "34e06f8a97459517384e01e5a84f4ac93efeb2e48c42ccb67620c2f5b23ead5df25b4aca2990176c48f34aa332706adedc2612614944d92d57bfb6b4b86e065c",
          "sha256": "430861e1b07ae080c350019fc9c63b331c19b5d8d469e32e898e3d6bbececc77",
          "sha1": "d010756e79fb1d20214fccc4139bde1ba50c6460",
          "md5": "d85d0244c86c082a008b85e4525b27cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.5+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.5+26.1.2-SNAPSHOT.jar",
          "size": 25810,
          "sha512": "34e06f8a97459517384e01e5a84f4ac93efeb2e48c42ccb67620c2f5b23ead5df25b4aca2990176c48f34aa332706adedc2612614944d92d57bfb6b4b86e065c",
          "sha256": "430861e1b07ae080c350019fc9c63b331c19b5d8d469e32e898e3d6bbececc77",
          "sha1": "d010756e79fb1d20214fccc4139bde1ba50c6460",
          "md5": "d85d0244c86c082a008b85e4525b27cf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.5+26.1.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.5+26.1.2-SNAPSHOT-sources.jar",
          "size": 14407,
          "sha512": "54b830f1ecf4ead6f129c347a57c9bd608d6b2edadb490c4212034e62c2fbaa8d86aee2a7186ee45e4d39d3b54b4a7f651dbc61a8a4d1899b6d43bdc32e81908",
          "sha256": "2be0708c0a4def6e74c1092c3e4ca5c9ae52ebec50f591d1862bec41f09acd5d",
          "sha1": "f90b5315a4ce40f435edec609b79eb784950e466",
          "md5": "67be78b9fe2ed70d424483270b2b6c5c"
        }
      ]
    }
  ]
}
