{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.13+26.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.13+26.3.jar",
          "url": "vaw-api-1.0.13+26.3.jar",
          "size": 26934,
          "sha512": "8a10d7e94fa958989fa08ce7e89d567f6a897d27bc274d1104d77da3a91c7f0cbc06e4c8a281fa9532ce66b7c8310e64206f82a65e4f3c2dad90375dd06d1650",
          "sha256": "9a03dd4461ea61b5ccdd273882d51d88d7d96febf6746fc7779759582835511c",
          "sha1": "31f04ad2292b6df8799761a8f01e1e6b3edac159",
          "md5": "6052626c29ec8e6f6c511d03654873a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.13+26.3.jar",
          "url": "vaw-api-1.0.13+26.3.jar",
          "size": 26934,
          "sha512": "8a10d7e94fa958989fa08ce7e89d567f6a897d27bc274d1104d77da3a91c7f0cbc06e4c8a281fa9532ce66b7c8310e64206f82a65e4f3c2dad90375dd06d1650",
          "sha256": "9a03dd4461ea61b5ccdd273882d51d88d7d96febf6746fc7779759582835511c",
          "sha1": "31f04ad2292b6df8799761a8f01e1e6b3edac159",
          "md5": "6052626c29ec8e6f6c511d03654873a6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.13+26.3-sources.jar",
          "url": "vaw-api-1.0.13+26.3-sources.jar",
          "size": 14615,
          "sha512": "ffe28966585a0476dc361a5f769a4fc87c66b84bc5c18878618cc4599aa02edb8cfe7165d98db44bce2aa5c06f7fd8fdf214499fecb5158e801f91d509a03a89",
          "sha256": "a84fa2fead9c93f1fabfb5f4f8656da3ab6b3679bba5cbecc663cb802b71ae86",
          "sha1": "888b892d9a4a4d5fc4197f5871c73ce2403d6d9d",
          "md5": "c948ae243b789f4f716a0a5cfa3265a9"
        }
      ]
    }
  ]
}
