{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.9.5+26.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.5+26.3.jar",
          "url": "vaw-api-0.9.5+26.3.jar",
          "size": 16216,
          "sha512": "d663075c8c436830dfaed64a6a4d63df9e6f524c273a0d8447fb77da3bebb5c02f076157cbb91c852451d9f1948e89d2eaa1ff7ee4e9f16b9cd1f346ca1b025b",
          "sha256": "c09ea0891145383381d4044eb5fb2edef16d1990fb594ee6f416e1dfa31aee51",
          "sha1": "7d3054e1a1ec61a8667e16bc242fc3b14253d2bc",
          "md5": "b587cb2f0d08d036b16eb56250458d12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.5+26.3.jar",
          "url": "vaw-api-0.9.5+26.3.jar",
          "size": 16216,
          "sha512": "d663075c8c436830dfaed64a6a4d63df9e6f524c273a0d8447fb77da3bebb5c02f076157cbb91c852451d9f1948e89d2eaa1ff7ee4e9f16b9cd1f346ca1b025b",
          "sha256": "c09ea0891145383381d4044eb5fb2edef16d1990fb594ee6f416e1dfa31aee51",
          "sha1": "7d3054e1a1ec61a8667e16bc242fc3b14253d2bc",
          "md5": "b587cb2f0d08d036b16eb56250458d12"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.9.5+26.3-sources.jar",
          "url": "vaw-api-0.9.5+26.3-sources.jar",
          "size": 7861,
          "sha512": "496306528cb7d459ae5c54df4fab63c50315dfab8df3f96a43f6bbf615621fca5ddad4b2ea44d0bf56378eb5393a132b19c9d8ceaae4c6018b559d7fd2ede201",
          "sha256": "ff6a879b8049504bd1ba1eb99e01c926eea3ef9c5add0ac2a6781cd658ebdfc6",
          "sha1": "3d289c41b1af11e269338cadbe310e255184f63e",
          "md5": "ac0dea5b3484c057b2ac12457bd15101"
        }
      ]
    }
  ]
}
