{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.10.1+26.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.1+26.2-SNAPSHOT.jar",
          "url": "vaw-api-0.10.1+26.2-SNAPSHOT.jar",
          "size": 18474,
          "sha512": "3df545784b2e4b1e1f9985b8e7440b3f696f4af31a9045ac464cdd54007c081d83c5ee87b3ced1a36efb34a3b9fc18b6ece06f9111f37f2074f89b6895d3819f",
          "sha256": "575f871b3100c919ec9181c3d3cb435c9bf11f4d0447f36bc904f8568b567592",
          "sha1": "9322c8b6dafce2be6fc6a45e1b1da7227a43deb0",
          "md5": "9fccdfb45591761cb2b9beb7f03aa06f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.1+26.2-SNAPSHOT.jar",
          "url": "vaw-api-0.10.1+26.2-SNAPSHOT.jar",
          "size": 18474,
          "sha512": "3df545784b2e4b1e1f9985b8e7440b3f696f4af31a9045ac464cdd54007c081d83c5ee87b3ced1a36efb34a3b9fc18b6ece06f9111f37f2074f89b6895d3819f",
          "sha256": "575f871b3100c919ec9181c3d3cb435c9bf11f4d0447f36bc904f8568b567592",
          "sha1": "9322c8b6dafce2be6fc6a45e1b1da7227a43deb0",
          "md5": "9fccdfb45591761cb2b9beb7f03aa06f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.10.1+26.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-0.10.1+26.2-SNAPSHOT-sources.jar",
          "size": 10005,
          "sha512": "eaa87e2a945fa6bfbc83d3e477f65484cbfc78ebee8488776f904dd061e522dcb310545748e994941d1e5f567769ea108300a96eedfc883ed96489b7829d2e44",
          "sha256": "03115d5d82aec252c0e494711bf5e0e712509443e039edfeeea1ab1e06ff55b7",
          "sha1": "4d9da97d1e71ee65bf0abb3ef53eca1941294393",
          "md5": "a6bea7faaf026803122c2b437975debb"
        }
      ]
    }
  ]
}
