{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.10.6+26.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.6+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-0.10.6+26.1.2-SNAPSHOT.jar",
          "size": 20098,
          "sha512": "a2ded9a9caa7576421de1d79eaa66f574201392dd9fc04b2579aaa975698a7aea3ea07779fefe943bf52014d10827708d36bf7592a74db8e86c13fd3cfc2599a",
          "sha256": "77d39c111bbd1daa4b19082b8d282cc9312e1508bfdd0b44da5afef53e292a5c",
          "sha1": "6cb5d4abc45b3719cb768a75c4cbc590104c1076",
          "md5": "149ff7ac627be6399984ff1f81af4bc4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.6+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-0.10.6+26.1.2-SNAPSHOT.jar",
          "size": 20098,
          "sha512": "a2ded9a9caa7576421de1d79eaa66f574201392dd9fc04b2579aaa975698a7aea3ea07779fefe943bf52014d10827708d36bf7592a74db8e86c13fd3cfc2599a",
          "sha256": "77d39c111bbd1daa4b19082b8d282cc9312e1508bfdd0b44da5afef53e292a5c",
          "sha1": "6cb5d4abc45b3719cb768a75c4cbc590104c1076",
          "md5": "149ff7ac627be6399984ff1f81af4bc4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.10.6+26.1.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-0.10.6+26.1.2-SNAPSHOT-sources.jar",
          "size": 11437,
          "sha512": "233a636dda98ba30256e366f2d469a77069e3967e11f4244bbd561ad6f1c88b38e17bde8b56b27b991f1793b99813f500e52fb9c0528c35957b3128cc0d08830",
          "sha256": "94b84fd0486027755c81c4141b65d6fac9a4aaff51a9f5a30696f67dd363b2fc",
          "sha1": "3e3c75688dfe4dd2923344b5d960c712f10b976c",
          "md5": "2f4a800329c6554b984b594e4c876c40"
        }
      ]
    }
  ]
}
