{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.10.5+26.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.5+26.1.2.jar",
          "url": "vaw-api-0.10.5+26.1.2.jar",
          "size": 19220,
          "sha512": "2389aab8b821cb3b1c96235b5e4ec317cf5bf846937f4ff4aea9086474f6d1766a51a85bcb56c0063af467674ae1699d215a9c4fc2c58596e0d110cf3e31def5",
          "sha256": "ae839bf5d9038e0b0bf99980887d96f08066938aaf5d82eb3dd2e241efb0e0cf",
          "sha1": "c2262433156ab6a7e67b133492cf93024066364d",
          "md5": "7fe5b4250a0fa1210bbc12daa9ac9ef8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.5+26.1.2.jar",
          "url": "vaw-api-0.10.5+26.1.2.jar",
          "size": 19220,
          "sha512": "2389aab8b821cb3b1c96235b5e4ec317cf5bf846937f4ff4aea9086474f6d1766a51a85bcb56c0063af467674ae1699d215a9c4fc2c58596e0d110cf3e31def5",
          "sha256": "ae839bf5d9038e0b0bf99980887d96f08066938aaf5d82eb3dd2e241efb0e0cf",
          "sha1": "c2262433156ab6a7e67b133492cf93024066364d",
          "md5": "7fe5b4250a0fa1210bbc12daa9ac9ef8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.10.5+26.1.2-sources.jar",
          "url": "vaw-api-0.10.5+26.1.2-sources.jar",
          "size": 10747,
          "sha512": "c7027b1907762b930ed451e166e3872dd79db4ece8642857612b47d45f7817d0e0b0364fa98db834b18beb105fe9472f00cb093f256a146bd260f70da430962e",
          "sha256": "986acef839dca2d8439a89473372003b5665f0456d0f183c04f2818a53004c25",
          "sha1": "b74385e6146287c2da160fbb057436eb7623b44f",
          "md5": "1a6db57be6997c044f7be262d883adac"
        }
      ]
    }
  ]
}
