{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.9.13+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.13+26.2.jar",
          "url": "vaw-api-0.9.13+26.2.jar",
          "size": 16362,
          "sha512": "1823edf4c4f855adc5ef1db21edea6c4caef9fbbc56e157b0e931fa73f6fec0990bf47cf5bd1be94f180f2adca6960a64b1c4a08ab53f24e53fc5b46c436cc19",
          "sha256": "1ea95325dc0cc0897b2f8de644154eacbda402d8500544b44bcbd3ce77ca3d79",
          "sha1": "534933ed701802cf881419c37f61dbe7946207b1",
          "md5": "a4e2db724de844c8b000f4949ba9e085"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.13+26.2.jar",
          "url": "vaw-api-0.9.13+26.2.jar",
          "size": 16362,
          "sha512": "1823edf4c4f855adc5ef1db21edea6c4caef9fbbc56e157b0e931fa73f6fec0990bf47cf5bd1be94f180f2adca6960a64b1c4a08ab53f24e53fc5b46c436cc19",
          "sha256": "1ea95325dc0cc0897b2f8de644154eacbda402d8500544b44bcbd3ce77ca3d79",
          "sha1": "534933ed701802cf881419c37f61dbe7946207b1",
          "md5": "a4e2db724de844c8b000f4949ba9e085"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.9.13+26.2-sources.jar",
          "url": "vaw-api-0.9.13+26.2-sources.jar",
          "size": 8055,
          "sha512": "ad46840dc85156f577ef3dc1a3068997bc5cc69f0761b44e0b17d3e4b210fee9eae413ed6c089ef32d594f5311b3f33fe36f805488f95f60d2264c3c1af915e0",
          "sha256": "b967a51fe643a0f1054592f9b724ea1c81d3b0535e0c81b3e4ae4b262cea3906",
          "sha1": "05ba2cd5a02a83405aac08c8441dd510105ed81f",
          "md5": "cc770a75b181c6554818130aed675e24"
        }
      ]
    }
  ]
}
