{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.9.12+26.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.12+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-0.9.12+26.1.2-SNAPSHOT.jar",
          "size": 16373,
          "sha512": "1dbf4d4199ecce08c3229c7f298fdac4dd93ac217da4233571d2e148f874b94ca397f9d9d575b223879e8890d3953fc81b9450c3449e1ebc4b9e0645ec746ec1",
          "sha256": "d9f1f58096a0ab995ac0f19efa28993697465f23ddcec759f37133862641a167",
          "sha1": "d8674980787af2b8e5e3b0c1d3d324b8c52d8dab",
          "md5": "571774f423506d29a4a4c0a22ffd42f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.12+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-0.9.12+26.1.2-SNAPSHOT.jar",
          "size": 16373,
          "sha512": "1dbf4d4199ecce08c3229c7f298fdac4dd93ac217da4233571d2e148f874b94ca397f9d9d575b223879e8890d3953fc81b9450c3449e1ebc4b9e0645ec746ec1",
          "sha256": "d9f1f58096a0ab995ac0f19efa28993697465f23ddcec759f37133862641a167",
          "sha1": "d8674980787af2b8e5e3b0c1d3d324b8c52d8dab",
          "md5": "571774f423506d29a4a4c0a22ffd42f5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.9.12+26.1.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-0.9.12+26.1.2-SNAPSHOT-sources.jar",
          "size": 8059,
          "sha512": "6f5ddc94fa6904c87ff7b96c7660cd8ae873444718aca45c92f60d40e79e7221668601fd0980d89aca4835377fce0140482f623177a27d699c48d07e36fab27b",
          "sha256": "e7702817f7f075441f0dd29886a097308c895f64d22a0551a092c602639a3bf9",
          "sha1": "2e099123f34ab499ad7bf0d373ac727da6655845",
          "md5": "b4d8248deb7da31627f670f7b4bd75b2"
        }
      ]
    }
  ]
}
