{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.9.8+26.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.8+26.3-SNAPSHOT.jar",
          "url": "vaw-api-0.9.8+26.3-SNAPSHOT.jar",
          "size": 16226,
          "sha512": "6e9e0e1e76227630ba175ac5f3eddf14ea912dd08cf9ba993c8c79c4d8e890bc7e319602b390195313a3803020924d7e2d642338139b437cfbaf8d11e2da78b6",
          "sha256": "63af10d39f865693957b7d4bb56303bed7d98e27bc185d3e362fa770a9f1007c",
          "sha1": "538262ffa447b3041b606362e74c8685e2e7cc75",
          "md5": "dfb745996ef1a9b063f6f2bcedeb9449"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.8+26.3-SNAPSHOT.jar",
          "url": "vaw-api-0.9.8+26.3-SNAPSHOT.jar",
          "size": 16226,
          "sha512": "6e9e0e1e76227630ba175ac5f3eddf14ea912dd08cf9ba993c8c79c4d8e890bc7e319602b390195313a3803020924d7e2d642338139b437cfbaf8d11e2da78b6",
          "sha256": "63af10d39f865693957b7d4bb56303bed7d98e27bc185d3e362fa770a9f1007c",
          "sha1": "538262ffa447b3041b606362e74c8685e2e7cc75",
          "md5": "dfb745996ef1a9b063f6f2bcedeb9449"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.9.8+26.3-SNAPSHOT-sources.jar",
          "url": "vaw-api-0.9.8+26.3-SNAPSHOT-sources.jar",
          "size": 7861,
          "sha512": "496306528cb7d459ae5c54df4fab63c50315dfab8df3f96a43f6bbf615621fca5ddad4b2ea44d0bf56378eb5393a132b19c9d8ceaae4c6018b559d7fd2ede201",
          "sha256": "ff6a879b8049504bd1ba1eb99e01c926eea3ef9c5add0ac2a6781cd658ebdfc6",
          "sha1": "3d289c41b1af11e269338cadbe310e255184f63e",
          "md5": "ac0dea5b3484c057b2ac12457bd15101"
        }
      ]
    }
  ]
}
