{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.3+26.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.3+26.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.3+26.2-SNAPSHOT.jar",
          "size": 24946,
          "sha512": "f9ac0df678eedf81ca4bc1c06c9bf2dc1f60866ced4c486b522eb346ad8927d69aac3f693089967e4ec5c330ecdf82e994fbb173c28037973f4393e0da9d8c84",
          "sha256": "f04dccabf64c024325ea45a01047f18701d85f3e73636c145334244b826f68ef",
          "sha1": "58a0fd77497cb221df5608f3381132533d6f6908",
          "md5": "566a9ea8240a3dc31ce2b8c5ab9c2228"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.3+26.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.3+26.2-SNAPSHOT.jar",
          "size": 24946,
          "sha512": "f9ac0df678eedf81ca4bc1c06c9bf2dc1f60866ced4c486b522eb346ad8927d69aac3f693089967e4ec5c330ecdf82e994fbb173c28037973f4393e0da9d8c84",
          "sha256": "f04dccabf64c024325ea45a01047f18701d85f3e73636c145334244b826f68ef",
          "sha1": "58a0fd77497cb221df5608f3381132533d6f6908",
          "md5": "566a9ea8240a3dc31ce2b8c5ab9c2228"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.3+26.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.3+26.2-SNAPSHOT-sources.jar",
          "size": 13756,
          "sha512": "54847fec9597cc0dbeaf311be75466e9987e1b4a036bf7c39fe255e1aa13248830caeb8429037c6b4b8714ade374be53c831aaa4b74fac591a48777ca3739f6a",
          "sha256": "9515e405697003c055e6a5db100bc3abf6307b29645eaf8a9e7ac71595eaac16",
          "sha1": "f0f7226ecc4dfd45464e24ba2ebf4653d998d16e",
          "md5": "052cf4c90ff87caaf8ef968e7b0bedcb"
        }
      ]
    }
  ]
}
