{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.10+26.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.10+26.3.jar",
          "url": "vaw-api-1.0.10+26.3.jar",
          "size": 26935,
          "sha512": "f20e72565dd709ef984dd2e00bc58fb30a5704930d1031812f8eeb98f4c4445676c8479cfcca51eeac0acc12dded1d3323882ca7c9812c8ae13722bf10199807",
          "sha256": "86363ec521e6aa0b4f2c003214379d939dbc901f7cc21712448cb2b76848b7cd",
          "sha1": "088b2cd1ddb05cc67e98625fe924563156b4393c",
          "md5": "742e670ea2a02cf97fab749c6314b843"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.10+26.3.jar",
          "url": "vaw-api-1.0.10+26.3.jar",
          "size": 26935,
          "sha512": "f20e72565dd709ef984dd2e00bc58fb30a5704930d1031812f8eeb98f4c4445676c8479cfcca51eeac0acc12dded1d3323882ca7c9812c8ae13722bf10199807",
          "sha256": "86363ec521e6aa0b4f2c003214379d939dbc901f7cc21712448cb2b76848b7cd",
          "sha1": "088b2cd1ddb05cc67e98625fe924563156b4393c",
          "md5": "742e670ea2a02cf97fab749c6314b843"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.10+26.3-sources.jar",
          "url": "vaw-api-1.0.10+26.3-sources.jar",
          "size": 14615,
          "sha512": "ffe28966585a0476dc361a5f769a4fc87c66b84bc5c18878618cc4599aa02edb8cfe7165d98db44bce2aa5c06f7fd8fdf214499fecb5158e801f91d509a03a89",
          "sha256": "a84fa2fead9c93f1fabfb5f4f8656da3ab6b3679bba5cbecc663cb802b71ae86",
          "sha1": "888b892d9a4a4d5fc4197f5871c73ce2403d6d9d",
          "md5": "c948ae243b789f4f716a0a5cfa3265a9"
        }
      ]
    }
  ]
}
