{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.9.1+26.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.1+26.1.2.jar",
          "url": "vaw-api-0.9.1+26.1.2.jar",
          "size": 16217,
          "sha512": "963d1e6eb6c2e2fdbc0dcbd25e7f77c8cf21696370446329d2eaf154afd90cd7734dd0cf378145c16319f5413d8223d58bd180e3b22a76bbb2f5ac0996c4500d",
          "sha256": "b8de9a3954e5bd9ce8019257bc284c6e92f20484933531d99204cfdaa7022252",
          "sha1": "728fe54ad11c6a50d4b8f4e4ba39700f5c975e5d",
          "md5": "b1add2154ef07ddc1cbf895e61a6fbdb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.1+26.1.2.jar",
          "url": "vaw-api-0.9.1+26.1.2.jar",
          "size": 16217,
          "sha512": "963d1e6eb6c2e2fdbc0dcbd25e7f77c8cf21696370446329d2eaf154afd90cd7734dd0cf378145c16319f5413d8223d58bd180e3b22a76bbb2f5ac0996c4500d",
          "sha256": "b8de9a3954e5bd9ce8019257bc284c6e92f20484933531d99204cfdaa7022252",
          "sha1": "728fe54ad11c6a50d4b8f4e4ba39700f5c975e5d",
          "md5": "b1add2154ef07ddc1cbf895e61a6fbdb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.9.1+26.1.2-sources.jar",
          "url": "vaw-api-0.9.1+26.1.2-sources.jar",
          "size": 7865,
          "sha512": "f9f2e96b22aa2b168bc58ed0c180c7a8d8a7debb268e26dd13598da884ffb2cdc9be7e21e675242453511208005b95113116504f085e105e78001462f9ffbf38",
          "sha256": "87376adf52ffd800d1a080b6e2b4aab8ffee877c969f46878a0ac383385ac1d6",
          "sha1": "fd697b7665401aae022719cf200b2f5e13a6fe27",
          "md5": "78f230fd0d00c7862de06db13fedc33f"
        }
      ]
    }
  ]
}
