{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.14+26.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.14+26.3-SNAPSHOT.jar",
          "url": "vaw-api-1.0.14+26.3-SNAPSHOT.jar",
          "size": 26946,
          "sha512": "9c520a8a6ecf4584c0211a561aa5cd52f02827cb15e8c279b85f4da5f6dfcbbba110ca1ed41253ffa66e0f6c80e0fe69b734f79d664ac6a485cbae6549a2f8a6",
          "sha256": "d0fea5a6605fd076e06c95a6de7c5210b96ce4ca860c3daa9d49f2f46719eb3a",
          "sha1": "90070f2bee9e196c08145c7451743f0d8f7889b9",
          "md5": "dd1b8392fc243bcbf603ad764f5c569f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.14+26.3-SNAPSHOT.jar",
          "url": "vaw-api-1.0.14+26.3-SNAPSHOT.jar",
          "size": 26946,
          "sha512": "9c520a8a6ecf4584c0211a561aa5cd52f02827cb15e8c279b85f4da5f6dfcbbba110ca1ed41253ffa66e0f6c80e0fe69b734f79d664ac6a485cbae6549a2f8a6",
          "sha256": "d0fea5a6605fd076e06c95a6de7c5210b96ce4ca860c3daa9d49f2f46719eb3a",
          "sha1": "90070f2bee9e196c08145c7451743f0d8f7889b9",
          "md5": "dd1b8392fc243bcbf603ad764f5c569f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.14+26.3-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.14+26.3-SNAPSHOT-sources.jar",
          "size": 14615,
          "sha512": "ffe28966585a0476dc361a5f769a4fc87c66b84bc5c18878618cc4599aa02edb8cfe7165d98db44bce2aa5c06f7fd8fdf214499fecb5158e801f91d509a03a89",
          "sha256": "a84fa2fead9c93f1fabfb5f4f8656da3ab6b3679bba5cbecc663cb802b71ae86",
          "sha1": "888b892d9a4a4d5fc4197f5871c73ce2403d6d9d",
          "md5": "c948ae243b789f4f716a0a5cfa3265a9"
        }
      ]
    }
  ]
}
