{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.10.6+26.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.6+26.2-SNAPSHOT.jar",
          "url": "vaw-api-0.10.6+26.2-SNAPSHOT.jar",
          "size": 20096,
          "sha512": "43845ca1ff74ede9bfcd1c8610d5f0c0faafd8c07470491d89dc4341987acadbb24bd42eb25c4fe00702b8c0aafc7f42ffdb3d96f521ad3d98e47d660f79efb5",
          "sha256": "bd0fcc6b238aee93dcd77cd40069b94d64e7c538ea5516ff8e0c1f30ef5c0ac1",
          "sha1": "5295e1652b177b9258494d74d3b1f42635b68176",
          "md5": "9226d0db0d5a4a9c18b8aa594b5d187f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.6+26.2-SNAPSHOT.jar",
          "url": "vaw-api-0.10.6+26.2-SNAPSHOT.jar",
          "size": 20096,
          "sha512": "43845ca1ff74ede9bfcd1c8610d5f0c0faafd8c07470491d89dc4341987acadbb24bd42eb25c4fe00702b8c0aafc7f42ffdb3d96f521ad3d98e47d660f79efb5",
          "sha256": "bd0fcc6b238aee93dcd77cd40069b94d64e7c538ea5516ff8e0c1f30ef5c0ac1",
          "sha1": "5295e1652b177b9258494d74d3b1f42635b68176",
          "md5": "9226d0db0d5a4a9c18b8aa594b5d187f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.10.6+26.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-0.10.6+26.2-SNAPSHOT-sources.jar",
          "size": 11433,
          "sha512": "25a52f98d277fbec984444d35226ae5730b082669de4e4341017b3eb03d6a175b0210a491339aade2c2f03981e47f230b2ed7669dd5f311b3cc8939f5f8abd71",
          "sha256": "45c62fc25d41f84b66f83522f33f70601a9eede86a8a85fab33c4b18c5ef25c9",
          "sha1": "0b8a869baa3fa7c9bfabb3c13574d8cb71b0abc4",
          "md5": "90d0c980eab2bfcc426c53298b492d45"
        }
      ]
    }
  ]
}
