{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.10+26.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.10+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.10+26.1.2-SNAPSHOT.jar",
          "size": 26947,
          "sha512": "54ceae2fda05bc8f424fd7fab3de0ed53276b2bdc7b082d2cf8b18a4e2b5e63e880fb3b8f9705321a97907d0f62f9ad26e8da45ce2df073b800c66a85caf0b47",
          "sha256": "2f98199d702c129312559bb2316720b1f59a5fff37c663bab0fe9a100d165b97",
          "sha1": "759045ab16c66c6c6775030d844ada7055bf4a5c",
          "md5": "c74b3cc19045a063e644c888b8319c5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.10+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.10+26.1.2-SNAPSHOT.jar",
          "size": 26947,
          "sha512": "54ceae2fda05bc8f424fd7fab3de0ed53276b2bdc7b082d2cf8b18a4e2b5e63e880fb3b8f9705321a97907d0f62f9ad26e8da45ce2df073b800c66a85caf0b47",
          "sha256": "2f98199d702c129312559bb2316720b1f59a5fff37c663bab0fe9a100d165b97",
          "sha1": "759045ab16c66c6c6775030d844ada7055bf4a5c",
          "md5": "c74b3cc19045a063e644c888b8319c5d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.10+26.1.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.10+26.1.2-SNAPSHOT-sources.jar",
          "size": 14619,
          "sha512": "c478c75ef63ed95fa767aa93dd61156675716e5e3267c4b2e199e9420302471db6cbc0161237202e36fb1d70d37e66bd943959f76b2073b1949555d76ba026a5",
          "sha256": "075f111e26f4b20d6bc2435a4317fc42e19a4c51245afa5a9c84a1b3204aad97",
          "sha1": "49385236b810e9d58f42c90aa5fd1deaa04278e2",
          "md5": "c964b72b42a879b9780dcc7ae10b81a4"
        }
      ]
    }
  ]
}
