{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.9.10+26.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.10+26.3-SNAPSHOT.jar",
          "url": "vaw-api-0.9.10+26.3-SNAPSHOT.jar",
          "size": 16227,
          "sha512": "e71038c73697f66e01cec1d1fea32973879de6335a6545f118a2b8b344ceff978ac23daa75747c699d34981ee86d5da6596158eb12ef56e7c7a71647e6538776",
          "sha256": "9b7a6f703261a32a1bccd29f267cd70c1430ed2214c83b8f47a6a3f81d6b5172",
          "sha1": "4bdd87ffa6ba3bcda8af34437ba3a469e2b637ef",
          "md5": "d59b366d5e3c796ca704647d313f13f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.10+26.3-SNAPSHOT.jar",
          "url": "vaw-api-0.9.10+26.3-SNAPSHOT.jar",
          "size": 16227,
          "sha512": "e71038c73697f66e01cec1d1fea32973879de6335a6545f118a2b8b344ceff978ac23daa75747c699d34981ee86d5da6596158eb12ef56e7c7a71647e6538776",
          "sha256": "9b7a6f703261a32a1bccd29f267cd70c1430ed2214c83b8f47a6a3f81d6b5172",
          "sha1": "4bdd87ffa6ba3bcda8af34437ba3a469e2b637ef",
          "md5": "d59b366d5e3c796ca704647d313f13f7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.9.10+26.3-SNAPSHOT-sources.jar",
          "url": "vaw-api-0.9.10+26.3-SNAPSHOT-sources.jar",
          "size": 7861,
          "sha512": "496306528cb7d459ae5c54df4fab63c50315dfab8df3f96a43f6bbf615621fca5ddad4b2ea44d0bf56378eb5393a132b19c9d8ceaae4c6018b559d7fd2ede201",
          "sha256": "ff6a879b8049504bd1ba1eb99e01c926eea3ef9c5add0ac2a6781cd658ebdfc6",
          "sha1": "3d289c41b1af11e269338cadbe310e255184f63e",
          "md5": "ac0dea5b3484c057b2ac12457bd15101"
        }
      ]
    }
  ]
}
