{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.1.0+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.1.0+26.2.jar",
          "url": "vaw-api-1.1.0+26.2.jar",
          "size": 62110,
          "sha512": "5070b995742253c9df62c8a7e57408aadeb42d61401e9be9e286ed86dd5566a8764cb6345041810c04bcb0883b8c6021dbaf77c4a322352713dd9e247e16de4d",
          "sha256": "c558e6eabfc38357f929412805b27ad92d0ee440397e0cad46db269f6ae21c26",
          "sha1": "7c12a9e27f50b1bc537ead9070ffac429796e48e",
          "md5": "a885cad4f09129ae0a9d928a6cf68e12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.1.0+26.2.jar",
          "url": "vaw-api-1.1.0+26.2.jar",
          "size": 62110,
          "sha512": "5070b995742253c9df62c8a7e57408aadeb42d61401e9be9e286ed86dd5566a8764cb6345041810c04bcb0883b8c6021dbaf77c4a322352713dd9e247e16de4d",
          "sha256": "c558e6eabfc38357f929412805b27ad92d0ee440397e0cad46db269f6ae21c26",
          "sha1": "7c12a9e27f50b1bc537ead9070ffac429796e48e",
          "md5": "a885cad4f09129ae0a9d928a6cf68e12"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.1.0+26.2-sources.jar",
          "url": "vaw-api-1.1.0+26.2-sources.jar",
          "size": 45138,
          "sha512": "7f2e80bf7f764094eee6436b92164e2c9870dba77c2b7b1ee75a1866d7192dc28874861401a3dc6a1d8dad4c86013b49c14359d54689ac4e30523c0d760bbc9e",
          "sha256": "b81071e24302a67ffa602c301f8783585345455c70779bbf3ef91e1b20984932",
          "sha1": "47e5910e95320ad13272f24c1e3a16496c47ee82",
          "md5": "8bb283258c69b28ab41c474b2828ea5b"
        }
      ]
    }
  ]
}
