{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.8+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.8+26.2.jar",
          "url": "vaw-api-1.0.8+26.2.jar",
          "size": 26936,
          "sha512": "afd3909a4d6702f56b035b81ccca4526b5724bd69760ec5c9b470e19718209104a61888578412cbb08edf73ab1450839af4793f75ab7c02cc2def2808bb388d4",
          "sha256": "f5c41f56de3b342f29f091001c9f25375eb990a73ae1b44b27e63552629b55a0",
          "sha1": "aa19c89e4eba5a5c10f06d56b2c4296ecf6a39aa",
          "md5": "e3736bb0248d81e52bf347f5f7096c52"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.8+26.2.jar",
          "url": "vaw-api-1.0.8+26.2.jar",
          "size": 26936,
          "sha512": "afd3909a4d6702f56b035b81ccca4526b5724bd69760ec5c9b470e19718209104a61888578412cbb08edf73ab1450839af4793f75ab7c02cc2def2808bb388d4",
          "sha256": "f5c41f56de3b342f29f091001c9f25375eb990a73ae1b44b27e63552629b55a0",
          "sha1": "aa19c89e4eba5a5c10f06d56b2c4296ecf6a39aa",
          "md5": "e3736bb0248d81e52bf347f5f7096c52"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.8+26.2-sources.jar",
          "url": "vaw-api-1.0.8+26.2-sources.jar",
          "size": 14615,
          "sha512": "672a54df014af689d3370ad647ffc802dfca614fb8f4b66a2567dec076d97bfdf2d36102d3b7d82b452f88804f5f76f547323768b5ffe229bcf476074ffaccb8",
          "sha256": "85f7da72e1b90b56676092dd1a1985741dd547944cd2cb56f1f265428f396c3a",
          "sha1": "b283e2e049cdd100e42b041c6d7a5b2b3bd27e4a",
          "md5": "3504a1b08060783a4cc98c70b8e575b6"
        }
      ]
    }
  ]
}
