{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.5+26.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.5+26.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.5+26.2-SNAPSHOT.jar",
          "size": 25807,
          "sha512": "609d6efae2151d57e61fb4eebc6fdd889f84ec45a054fc6b87abdd9aa0e5d1122156aa09796972779f9ed9899d9011fd526ca34dffa1d404cb28b0d0e86ad797",
          "sha256": "113073197a48a6b4c79df43f61713a5cba968743c9e409e41f12d2f72440a3b3",
          "sha1": "e62fb8584e8eb0134790099429fb698690cb2c5f",
          "md5": "7c180c47038b81c8964fd93c1fa98d8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.5+26.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.5+26.2-SNAPSHOT.jar",
          "size": 25807,
          "sha512": "609d6efae2151d57e61fb4eebc6fdd889f84ec45a054fc6b87abdd9aa0e5d1122156aa09796972779f9ed9899d9011fd526ca34dffa1d404cb28b0d0e86ad797",
          "sha256": "113073197a48a6b4c79df43f61713a5cba968743c9e409e41f12d2f72440a3b3",
          "sha1": "e62fb8584e8eb0134790099429fb698690cb2c5f",
          "md5": "7c180c47038b81c8964fd93c1fa98d8f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.5+26.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.5+26.2-SNAPSHOT-sources.jar",
          "size": 14403,
          "sha512": "62a5c3a3e250015d41f733ad0ac5adddbf7a8304a8da1c407b9a1843182e52f8d206cda579903eeee4d92cedcf406ee7a1107567d8a12ef8bc908b7cee515158",
          "sha256": "9e2fffe786a57e658389ebff5808b1a0d1fb3f7c4ad74aca31e05b73d0971268",
          "sha1": "d2dacb7c5f9126746efa2057b9fccf4fae908f01",
          "md5": "61c35276c94dc5951d6f10673e68f73e"
        }
      ]
    }
  ]
}
