{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.1.0+26.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.1.0+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-0.1.0+26.1.2-SNAPSHOT.jar",
          "size": 10768,
          "sha512": "da98c4402b03c9a6df96238cc141e9bca3f4b104d935e11adaa003ea8352251299a8b028ac29604f187d9ad418bba3c8987b06e27376ade64b814682bacae9f2",
          "sha256": "1011f25da763cab2ec8a0e2ee833cbe77f0866af894857a32f93424a594e5200",
          "sha1": "3cfcc172a9e22b0d9ffd7a3f8d70af8854fcb09f",
          "md5": "2e65dc5ca2aa3953042946f5a026641e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.1.0+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-0.1.0+26.1.2-SNAPSHOT.jar",
          "size": 10768,
          "sha512": "da98c4402b03c9a6df96238cc141e9bca3f4b104d935e11adaa003ea8352251299a8b028ac29604f187d9ad418bba3c8987b06e27376ade64b814682bacae9f2",
          "sha256": "1011f25da763cab2ec8a0e2ee833cbe77f0866af894857a32f93424a594e5200",
          "sha1": "3cfcc172a9e22b0d9ffd7a3f8d70af8854fcb09f",
          "md5": "2e65dc5ca2aa3953042946f5a026641e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.1.0+26.1.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-0.1.0+26.1.2-SNAPSHOT-sources.jar",
          "size": 5756,
          "sha512": "f09b718d42e28012472d91e06da58f564d13a2ca736a94b5669cd1cc301b5e1954013de1911f13ef539014989bccb22e767eb4a46b4ad3cabd1a3504c38176e0",
          "sha256": "ba61d66429996744d1d8775b9ab26dba6a6a02a8783bd6db1c0fbed5e79d6137",
          "sha1": "4c6112e000b2ed825b8682232027b953df283256",
          "md5": "e905beb09792d280a7d5adc5479419c3"
        }
      ]
    }
  ]
}
