{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.8+26.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.8+26.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.8+26.2-SNAPSHOT.jar",
          "size": 26944,
          "sha512": "3693f62a1ec2833e8f3e8c496f02d5112e7927f40209f7ad512d56464ee45fae6bafc35d5d13d0e6574792c984ea70907f7196d42cc65130012d2b29b32fdb0d",
          "sha256": "d5beab2d733222bdcb7976d7df1b6d2af2f5680b432627741c00a08a040ce838",
          "sha1": "151a8df0c9fd726bce7da08b36537738a21b061d",
          "md5": "1b773002110b3782ea24ee5e01dc0174"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.8+26.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.8+26.2-SNAPSHOT.jar",
          "size": 26944,
          "sha512": "3693f62a1ec2833e8f3e8c496f02d5112e7927f40209f7ad512d56464ee45fae6bafc35d5d13d0e6574792c984ea70907f7196d42cc65130012d2b29b32fdb0d",
          "sha256": "d5beab2d733222bdcb7976d7df1b6d2af2f5680b432627741c00a08a040ce838",
          "sha1": "151a8df0c9fd726bce7da08b36537738a21b061d",
          "md5": "1b773002110b3782ea24ee5e01dc0174"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.8+26.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.8+26.2-SNAPSHOT-sources.jar",
          "size": 14615,
          "sha512": "672a54df014af689d3370ad647ffc802dfca614fb8f4b66a2567dec076d97bfdf2d36102d3b7d82b452f88804f5f76f547323768b5ffe229bcf476074ffaccb8",
          "sha256": "85f7da72e1b90b56676092dd1a1985741dd547944cd2cb56f1f265428f396c3a",
          "sha1": "b283e2e049cdd100e42b041c6d7a5b2b3bd27e4a",
          "md5": "3504a1b08060783a4cc98c70b8e575b6"
        }
      ]
    }
  ]
}
