{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.2+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.2+26.2.jar",
          "url": "vaw-api-1.0.2+26.2.jar",
          "size": 24937,
          "sha512": "ccf36dab322c5513f0a887ca6d38ffbc403d7fb6778b4bca4843b0394297f883826a1f1316ef50b8eee9c63a4c3c14fe44f29bde72778bdb4d9dad303e9fb891",
          "sha256": "d67ee19d1171e8a10cf7ada1baf3a5c510034ae225fb8f9d0550a76dbe0058f8",
          "sha1": "13735209e2ab4e66566e8f450935b3f5ba36786e",
          "md5": "845087939302af2b32f21f90db391e3f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.2+26.2.jar",
          "url": "vaw-api-1.0.2+26.2.jar",
          "size": 24937,
          "sha512": "ccf36dab322c5513f0a887ca6d38ffbc403d7fb6778b4bca4843b0394297f883826a1f1316ef50b8eee9c63a4c3c14fe44f29bde72778bdb4d9dad303e9fb891",
          "sha256": "d67ee19d1171e8a10cf7ada1baf3a5c510034ae225fb8f9d0550a76dbe0058f8",
          "sha1": "13735209e2ab4e66566e8f450935b3f5ba36786e",
          "md5": "845087939302af2b32f21f90db391e3f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.2+26.2-sources.jar",
          "url": "vaw-api-1.0.2+26.2-sources.jar",
          "size": 13756,
          "sha512": "54847fec9597cc0dbeaf311be75466e9987e1b4a036bf7c39fe255e1aa13248830caeb8429037c6b4b8714ade374be53c831aaa4b74fac591a48777ca3739f6a",
          "sha256": "9515e405697003c055e6a5db100bc3abf6307b29645eaf8a9e7ac71595eaac16",
          "sha1": "f0f7226ecc4dfd45464e24ba2ebf4653d998d16e",
          "md5": "052cf4c90ff87caaf8ef968e7b0bedcb"
        }
      ]
    }
  ]
}
