{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.9.4+26.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.4+26.2-SNAPSHOT.jar",
          "url": "vaw-api-0.9.4+26.2-SNAPSHOT.jar",
          "size": 16225,
          "sha512": "ab51ca41486f123a2aae424c7e0b4016c0592feeac72e671530317819eded2882452447e5dd7ba938ba221c22563984149345007c299adb418cfbef0bd0bf7d3",
          "sha256": "925093436bbcc3a4123bc9451742ac3ee6ccb685784589b01b1ba9ad96917c52",
          "sha1": "2f736ce4264a24eefb81ba2fbe9a67bbadfed8d1",
          "md5": "6bf7f60c6e0a13b768fe94b2b255e3ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.4+26.2-SNAPSHOT.jar",
          "url": "vaw-api-0.9.4+26.2-SNAPSHOT.jar",
          "size": 16225,
          "sha512": "ab51ca41486f123a2aae424c7e0b4016c0592feeac72e671530317819eded2882452447e5dd7ba938ba221c22563984149345007c299adb418cfbef0bd0bf7d3",
          "sha256": "925093436bbcc3a4123bc9451742ac3ee6ccb685784589b01b1ba9ad96917c52",
          "sha1": "2f736ce4264a24eefb81ba2fbe9a67bbadfed8d1",
          "md5": "6bf7f60c6e0a13b768fe94b2b255e3ae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.9.4+26.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-0.9.4+26.2-SNAPSHOT-sources.jar",
          "size": 7861,
          "sha512": "8876ea7bad3565b17e8b94b262ea3ae28a9577618e22515a17e0ea19f00f57744be243fcf63b1b7e35aaabd17d24bc0c3d14532f82e526bce7542b09e6d870a9",
          "sha256": "b4dc0b4e8017457ba9b46e9cabdffe083919c4c6c413d353c1060d905f11d151",
          "sha1": "f22ae6a343bc82220e690913a81da0fcc19cd6ba",
          "md5": "99f1d791e81dbb50573da9ccaaa3fc5a"
        }
      ]
    }
  ]
}
