{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.12+26.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.12+26.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.12+26.2-SNAPSHOT.jar",
          "size": 26945,
          "sha512": "04199f6daa16c85caa39e0513125b4ad276881543ff7e5dd13f4009fa1c6b65bba31346b219ef3105d738342c62b5d0edc18c63ac3511398ba472b2a47a94688",
          "sha256": "3ef0ed7b3f86f7760c7dabeb92c3c0abc8321a208da50605addb781e294da89f",
          "sha1": "8d6931be7bdd120c16d4145a588b680cc7e9d635",
          "md5": "27010c817902bb3d128210373ce1cddc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.12+26.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.12+26.2-SNAPSHOT.jar",
          "size": 26945,
          "sha512": "04199f6daa16c85caa39e0513125b4ad276881543ff7e5dd13f4009fa1c6b65bba31346b219ef3105d738342c62b5d0edc18c63ac3511398ba472b2a47a94688",
          "sha256": "3ef0ed7b3f86f7760c7dabeb92c3c0abc8321a208da50605addb781e294da89f",
          "sha1": "8d6931be7bdd120c16d4145a588b680cc7e9d635",
          "md5": "27010c817902bb3d128210373ce1cddc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.12+26.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.12+26.2-SNAPSHOT-sources.jar",
          "size": 14615,
          "sha512": "672a54df014af689d3370ad647ffc802dfca614fb8f4b66a2567dec076d97bfdf2d36102d3b7d82b452f88804f5f76f547323768b5ffe229bcf476074ffaccb8",
          "sha256": "85f7da72e1b90b56676092dd1a1985741dd547944cd2cb56f1f265428f396c3a",
          "sha1": "b283e2e049cdd100e42b041c6d7a5b2b3bd27e4a",
          "md5": "3504a1b08060783a4cc98c70b8e575b6"
        }
      ]
    }
  ]
}
