{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.10.3+26.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.3+26.1.2.jar",
          "url": "vaw-api-0.10.3+26.1.2.jar",
          "size": 18466,
          "sha512": "68bcb702b8d2fa945644203cb003a2b4333a67d712da0ae7d2b3890c6f543e7349c1f2e2959efe1bce51afaafe0e9c6d1d09da0641ad4f84ef1aab6326fab892",
          "sha256": "f2055d80355efb3ef634a05340519174c81a1b199fb846754bbef8422d758643",
          "sha1": "1e06dfba7571176584d51dad5addc1ad0d41b590",
          "md5": "2246215f6bdc686f306b10d2b10be7ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.3+26.1.2.jar",
          "url": "vaw-api-0.10.3+26.1.2.jar",
          "size": 18466,
          "sha512": "68bcb702b8d2fa945644203cb003a2b4333a67d712da0ae7d2b3890c6f543e7349c1f2e2959efe1bce51afaafe0e9c6d1d09da0641ad4f84ef1aab6326fab892",
          "sha256": "f2055d80355efb3ef634a05340519174c81a1b199fb846754bbef8422d758643",
          "sha1": "1e06dfba7571176584d51dad5addc1ad0d41b590",
          "md5": "2246215f6bdc686f306b10d2b10be7ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.10.3+26.1.2-sources.jar",
          "url": "vaw-api-0.10.3+26.1.2-sources.jar",
          "size": 10009,
          "sha512": "6ee8ef75c7f6b0a02149cbd17accf1b2f8bf39bcfa7e7a95670f81d440f52c5834eb35c876167cc119f65bbc45e35a9d67a41c08b598c68ca77ee547af7df0e2",
          "sha256": "637ed71da2198ae257e6e6b8d08b667ce0b747acf66ea97ed21807409002c0df",
          "sha1": "858677dea1fa876e17c4f56f8d2b1c6cde8740ca",
          "md5": "e8c522ef1820c4b06fd57a93927d71cd"
        }
      ]
    }
  ]
}
