{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.18+26.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.18+26.3-SNAPSHOT.jar",
          "url": "vaw-api-1.0.18+26.3-SNAPSHOT.jar",
          "size": 55566,
          "sha512": "522eb77e5941dd359b8463f21eba3609e2db6135d4a21d20e8839adf40a47eca364f43e47f0f59f045dd7a159d5695fedd418f881554edae608a57077536ef4e",
          "sha256": "a8a1a7e6b1ec8e1188329296023bc38a490e4599e2ce82ecc403022b4510dd92",
          "sha1": "c9caabee9e53fe71cad592b9763df1284a69ff22",
          "md5": "ec1b934e69fd3933ab669fb6a3ee3003"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.18+26.3-SNAPSHOT.jar",
          "url": "vaw-api-1.0.18+26.3-SNAPSHOT.jar",
          "size": 55566,
          "sha512": "522eb77e5941dd359b8463f21eba3609e2db6135d4a21d20e8839adf40a47eca364f43e47f0f59f045dd7a159d5695fedd418f881554edae608a57077536ef4e",
          "sha256": "a8a1a7e6b1ec8e1188329296023bc38a490e4599e2ce82ecc403022b4510dd92",
          "sha1": "c9caabee9e53fe71cad592b9763df1284a69ff22",
          "md5": "ec1b934e69fd3933ab669fb6a3ee3003"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.18+26.3-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.18+26.3-SNAPSHOT-sources.jar",
          "size": 43188,
          "sha512": "8fea454ca4bb5f82219404a30fd162b64bd28f69e30727939b7e1cd64eec06df0bea476dce11a826446f68cb80d37a2ac508d753547bc3929d967e5ce386221e",
          "sha256": "33ed5db5c68facd0b839010d56e257866903b1a5696cf004393d100322b58370",
          "sha1": "d518e2a88e91c9bc457f28c6ae572060d2336d14",
          "md5": "2ad4b2d2a69cf634fdc5737dbe870a4c"
        }
      ]
    }
  ]
}
