{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.10.2+26.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.2+26.3-SNAPSHOT.jar",
          "url": "vaw-api-0.10.2+26.3-SNAPSHOT.jar",
          "size": 18475,
          "sha512": "42715585870278853dd274d7410081fadfee08c3f506b2544a17275f537b46307aa2f69f512dc0f7b78d09d272b47813169d19e00e917e5765e39653c472e835",
          "sha256": "5afdbeaba8b6a6e2239623dff6ab4c4eef514d774acde1798d5ddfc720cb3409",
          "sha1": "795be4f44cf810c24d1ede13b17abc1642cb6d8c",
          "md5": "b1a4dc2f12bd2c85667da48a22324cd0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.2+26.3-SNAPSHOT.jar",
          "url": "vaw-api-0.10.2+26.3-SNAPSHOT.jar",
          "size": 18475,
          "sha512": "42715585870278853dd274d7410081fadfee08c3f506b2544a17275f537b46307aa2f69f512dc0f7b78d09d272b47813169d19e00e917e5765e39653c472e835",
          "sha256": "5afdbeaba8b6a6e2239623dff6ab4c4eef514d774acde1798d5ddfc720cb3409",
          "sha1": "795be4f44cf810c24d1ede13b17abc1642cb6d8c",
          "md5": "b1a4dc2f12bd2c85667da48a22324cd0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.10.2+26.3-SNAPSHOT-sources.jar",
          "url": "vaw-api-0.10.2+26.3-SNAPSHOT-sources.jar",
          "size": 10005,
          "sha512": "efcfbe3581092de672a78fe81b9d02725e1ac21e3ef0b8473a27db3bc6829be030224a6b01f527eda3823c416badbfe6f00a1d5467694b3560751f7c6d6a9463",
          "sha256": "d9327d61485633d65aa4b0bff030b24e29e95e6d046e0f573a9c3ba8b097829b",
          "sha1": "3fcd07c36e66d845847226dd116bb54583f6c2ab",
          "md5": "c79c102587a82ba4cb4e38d1978c0ba8"
        }
      ]
    }
  ]
}
