{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.9.12+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.12+26.2.jar",
          "url": "vaw-api-0.9.12+26.2.jar",
          "size": 16362,
          "sha512": "c9fa574f77420aefb515faf35580ce383151bfa9c32e51a3e80c58a1fa9b8d56eabf78f24c35a7671d83d503e39711ae00f68c55b0a19576afdc9791dd01598b",
          "sha256": "62f271bf49c4140db4266d35691d2556a69d6cfc14853133e3ee298286e4ba13",
          "sha1": "8ce8b20f53f016d23ad0e925c45d179c4e1b86f2",
          "md5": "31a0034ce76bb7ee82426c98493d16c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.12+26.2.jar",
          "url": "vaw-api-0.9.12+26.2.jar",
          "size": 16362,
          "sha512": "c9fa574f77420aefb515faf35580ce383151bfa9c32e51a3e80c58a1fa9b8d56eabf78f24c35a7671d83d503e39711ae00f68c55b0a19576afdc9791dd01598b",
          "sha256": "62f271bf49c4140db4266d35691d2556a69d6cfc14853133e3ee298286e4ba13",
          "sha1": "8ce8b20f53f016d23ad0e925c45d179c4e1b86f2",
          "md5": "31a0034ce76bb7ee82426c98493d16c3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.9.12+26.2-sources.jar",
          "url": "vaw-api-0.9.12+26.2-sources.jar",
          "size": 8055,
          "sha512": "ad46840dc85156f577ef3dc1a3068997bc5cc69f0761b44e0b17d3e4b210fee9eae413ed6c089ef32d594f5311b3f33fe36f805488f95f60d2264c3c1af915e0",
          "sha256": "b967a51fe643a0f1054592f9b724ea1c81d3b0535e0c81b3e4ae4b262cea3906",
          "sha1": "05ba2cd5a02a83405aac08c8441dd510105ed81f",
          "md5": "cc770a75b181c6554818130aed675e24"
        }
      ]
    }
  ]
}
