{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.10.5+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.5+26.2.jar",
          "url": "vaw-api-0.10.5+26.2.jar",
          "size": 19219,
          "sha512": "eca3f5a4621015c6fadc1212337401f34a2168ce20f9a776734c8d943fc5c559b9af62b7cc3ff81f71386c1a1f859ca94f366360c8ba97d4a0568217866585d4",
          "sha256": "5bc27ab05497fe1892e5eca834433c754c0fd2ad9600bb2752de506f2eea1cbb",
          "sha1": "fd59516018565799a2d50edb88088f28d9ee1cca",
          "md5": "fb07e0af6a1372917aeb0d429be36efe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.5+26.2.jar",
          "url": "vaw-api-0.10.5+26.2.jar",
          "size": 19219,
          "sha512": "eca3f5a4621015c6fadc1212337401f34a2168ce20f9a776734c8d943fc5c559b9af62b7cc3ff81f71386c1a1f859ca94f366360c8ba97d4a0568217866585d4",
          "sha256": "5bc27ab05497fe1892e5eca834433c754c0fd2ad9600bb2752de506f2eea1cbb",
          "sha1": "fd59516018565799a2d50edb88088f28d9ee1cca",
          "md5": "fb07e0af6a1372917aeb0d429be36efe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.10.5+26.2-sources.jar",
          "url": "vaw-api-0.10.5+26.2-sources.jar",
          "size": 10743,
          "sha512": "c874fb3ea045dd2b4c95a9b145628a44eaf73d34316422015fb180ba60da0459980ab9bb8397f5a2186a6304ce013e9be4607b2dfedebbde01124d11d362d13c",
          "sha256": "5adbe3fe352a286ec3d7b4d5f2d99d263d947b6f833efcd10c3d8bfb1db5237e",
          "sha1": "e33cfa430c42d7edb14de9feb3f4b7c1ab96b26a",
          "md5": "7204d8d494dbb5617ba473eb94b450a1"
        }
      ]
    }
  ]
}
