{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.1+26.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.1+26.3.jar",
          "url": "vaw-api-1.0.1+26.3.jar",
          "size": 24936,
          "sha512": "8b4bff8c32015b167f582d7fc6c2464dcf827b086dd5ac2a1f9a76a03f804de426c39b2f9e3909f4507c5db9d59fff3c77736f85c22c865f8f7c5aac09c4ced5",
          "sha256": "5b7c507af6e719fffeb3652e153341473c306439837a5441f5ede57a8f177e0c",
          "sha1": "c606cfa5d5fd9615dd5339a3c2fe52819e7dbd53",
          "md5": "34a60aac53dd1a56c08c7c221180b7f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.1+26.3.jar",
          "url": "vaw-api-1.0.1+26.3.jar",
          "size": 24936,
          "sha512": "8b4bff8c32015b167f582d7fc6c2464dcf827b086dd5ac2a1f9a76a03f804de426c39b2f9e3909f4507c5db9d59fff3c77736f85c22c865f8f7c5aac09c4ced5",
          "sha256": "5b7c507af6e719fffeb3652e153341473c306439837a5441f5ede57a8f177e0c",
          "sha1": "c606cfa5d5fd9615dd5339a3c2fe52819e7dbd53",
          "md5": "34a60aac53dd1a56c08c7c221180b7f6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.1+26.3-sources.jar",
          "url": "vaw-api-1.0.1+26.3-sources.jar",
          "size": 13756,
          "sha512": "a8170553e852221b02df8c7eb0df68ffd3ccc4cf9da75c2426cdcdaa2ee72a6ba5058b2db326c6d7f795b95d16d2a62cf552fb89fd50d4ea30da19b2d98b714b",
          "sha256": "f1eb72326c6f3163b5a4adcb8a7d5465908e7d9cae76523b2bfeb945b77dbcec",
          "sha1": "593b62708052853fd9d45e65cfa429129b5b0eac",
          "md5": "3c2053a9e4efdd7038b327ee6cf3679e"
        }
      ]
    }
  ]
}
