{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.10.6+26.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.6+26.1.2.jar",
          "url": "vaw-api-0.10.6+26.1.2.jar",
          "size": 20087,
          "sha512": "f236e872b9ad7fdcb90ee8fac211218210f45d7bc1cb7bc22bc2e815471dd6d63dd4dde4c37f4c0e004d7370d4a50fe7472647f8650c021c7ec71ef44be46e95",
          "sha256": "0202c140bec58f89256b745debbdc8cfb2a1af9790aaf96782c093460e0766ed",
          "sha1": "9bd35cf7f79744f9452486bdf3c4d53aac18fa82",
          "md5": "5d494f12fd297d49f8aa8fcad4265e00"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.6+26.1.2.jar",
          "url": "vaw-api-0.10.6+26.1.2.jar",
          "size": 20087,
          "sha512": "f236e872b9ad7fdcb90ee8fac211218210f45d7bc1cb7bc22bc2e815471dd6d63dd4dde4c37f4c0e004d7370d4a50fe7472647f8650c021c7ec71ef44be46e95",
          "sha256": "0202c140bec58f89256b745debbdc8cfb2a1af9790aaf96782c093460e0766ed",
          "sha1": "9bd35cf7f79744f9452486bdf3c4d53aac18fa82",
          "md5": "5d494f12fd297d49f8aa8fcad4265e00"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.10.6+26.1.2-sources.jar",
          "url": "vaw-api-0.10.6+26.1.2-sources.jar",
          "size": 11437,
          "sha512": "233a636dda98ba30256e366f2d469a77069e3967e11f4244bbd561ad6f1c88b38e17bde8b56b27b991f1793b99813f500e52fb9c0528c35957b3128cc0d08830",
          "sha256": "94b84fd0486027755c81c4141b65d6fac9a4aaff51a9f5a30696f67dd363b2fc",
          "sha1": "3e3c75688dfe4dd2923344b5d960c712f10b976c",
          "md5": "2f4a800329c6554b984b594e4c876c40"
        }
      ]
    }
  ]
}
