{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.16+26.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.16+26.3-SNAPSHOT.jar",
          "url": "vaw-api-1.0.16+26.3-SNAPSHOT.jar",
          "size": 55564,
          "sha512": "f1877a3e18ed32e4dd3e48c095f0066d4b26faedcd39236e7d6a8789f137947b7235b6cd56c4db4ab8b020567e0e0769c850148d59cc51c9d73e6a9d51f62bfe",
          "sha256": "c03f0d7f4d6434ab27e03973ef82bbc0f969278efbaf6013dbef275543d1a4d6",
          "sha1": "17c346a7b9a7263fb7f934440ff66c12aff8604f",
          "md5": "4bb0b5f70e9753c9e7adc3c374b9e0f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.16+26.3-SNAPSHOT.jar",
          "url": "vaw-api-1.0.16+26.3-SNAPSHOT.jar",
          "size": 55564,
          "sha512": "f1877a3e18ed32e4dd3e48c095f0066d4b26faedcd39236e7d6a8789f137947b7235b6cd56c4db4ab8b020567e0e0769c850148d59cc51c9d73e6a9d51f62bfe",
          "sha256": "c03f0d7f4d6434ab27e03973ef82bbc0f969278efbaf6013dbef275543d1a4d6",
          "sha1": "17c346a7b9a7263fb7f934440ff66c12aff8604f",
          "md5": "4bb0b5f70e9753c9e7adc3c374b9e0f8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.16+26.3-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.16+26.3-SNAPSHOT-sources.jar",
          "size": 43186,
          "sha512": "47d0037a16a5d2cc025e9e78dc12e3bdf9bf6e496519e553ecedb81049aff7ace243cb54273b2a35d6377b1c0532459e7efb4fe3fa9a621360178464f82a51d1",
          "sha256": "911f8d2a7d6b4e51aaee2a674d02f81820ed3d5939979bafa9db00b51d711623",
          "sha1": "27f9f24eb359de013ed38b4a1d1dfd71bfe45e8e",
          "md5": "9a4493a9dfa4e464a8f1bfa05e3a4645"
        }
      ]
    }
  ]
}
