{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.16+26.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.16+26.3-SNAPSHOT.jar",
          "url": "vaw-api-1.0.16+26.3-SNAPSHOT.jar",
          "size": 55566,
          "sha512": "504f86407a31aee6c37d67c6399277998357021a4fb4b179e71994d82bad93accfac05b7faa219c68d3dd284a0079283fa0808075b5f0336c6eb80fa4357c6c3",
          "sha256": "0777d0c517ead10094f66971c85138af113370280d1daa05903aea1a459d3c27",
          "sha1": "ca8b5e21860a445076b9c5e526d0a6583b3fbd18",
          "md5": "0d0117b260f2720f77b498575e5b9ad9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.16+26.3-SNAPSHOT.jar",
          "url": "vaw-api-1.0.16+26.3-SNAPSHOT.jar",
          "size": 55566,
          "sha512": "504f86407a31aee6c37d67c6399277998357021a4fb4b179e71994d82bad93accfac05b7faa219c68d3dd284a0079283fa0808075b5f0336c6eb80fa4357c6c3",
          "sha256": "0777d0c517ead10094f66971c85138af113370280d1daa05903aea1a459d3c27",
          "sha1": "ca8b5e21860a445076b9c5e526d0a6583b3fbd18",
          "md5": "0d0117b260f2720f77b498575e5b9ad9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.16+26.3-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.16+26.3-SNAPSHOT-sources.jar",
          "size": 43188,
          "sha512": "8fea454ca4bb5f82219404a30fd162b64bd28f69e30727939b7e1cd64eec06df0bea476dce11a826446f68cb80d37a2ac508d753547bc3929d967e5ce386221e",
          "sha256": "33ed5db5c68facd0b839010d56e257866903b1a5696cf004393d100322b58370",
          "sha1": "d518e2a88e91c9bc457f28c6ae572060d2336d14",
          "md5": "2ad4b2d2a69cf634fdc5737dbe870a4c"
        }
      ]
    }
  ]
}
