{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.10.5+26.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.5+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-0.10.5+26.1.2-SNAPSHOT.jar",
          "size": 19231,
          "sha512": "9da1b0c2f58078f7a806cf1742d439664bbff7b1218c137d8f9accc1496cf7e350d00c54f28f13f21ea0eaccc07f99ef10d2e411a15d63a8415cede237847be5",
          "sha256": "800d44bd11ae0ad81fa77a76177ad0994fe974085d79be45e3059e52b7fef509",
          "sha1": "602e6da8d92d874ecb4943031bda039199f1ab18",
          "md5": "6028606b279652a2d4393c58e16a9d15"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.5+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-0.10.5+26.1.2-SNAPSHOT.jar",
          "size": 19231,
          "sha512": "9da1b0c2f58078f7a806cf1742d439664bbff7b1218c137d8f9accc1496cf7e350d00c54f28f13f21ea0eaccc07f99ef10d2e411a15d63a8415cede237847be5",
          "sha256": "800d44bd11ae0ad81fa77a76177ad0994fe974085d79be45e3059e52b7fef509",
          "sha1": "602e6da8d92d874ecb4943031bda039199f1ab18",
          "md5": "6028606b279652a2d4393c58e16a9d15"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.10.5+26.1.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-0.10.5+26.1.2-SNAPSHOT-sources.jar",
          "size": 10747,
          "sha512": "c7027b1907762b930ed451e166e3872dd79db4ece8642857612b47d45f7817d0e0b0364fa98db834b18beb105fe9472f00cb093f256a146bd260f70da430962e",
          "sha256": "986acef839dca2d8439a89473372003b5665f0456d0f183c04f2818a53004c25",
          "sha1": "b74385e6146287c2da160fbb057436eb7623b44f",
          "md5": "1a6db57be6997c044f7be262d883adac"
        }
      ]
    }
  ]
}
