{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.18+26.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.18+26.3.jar",
          "url": "vaw-api-1.0.18+26.3.jar",
          "size": 55555,
          "sha512": "4571c3eca68b6820e1e9df31d52e88b9a96fb03e2182323aeccf3ee51f049602cf946f1c360aeab5161c4aff1d48d76602524121aa00da7c85542cec2b8b95ac",
          "sha256": "883e2776bdeae2781f3c47a0a93925066fadc6f7b692286352527a4e925ae8ed",
          "sha1": "fef0b1f846d528c9808d6d43a7830a47375e98d2",
          "md5": "d9df66ab9ecac39b357b0d7e91829146"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.18+26.3.jar",
          "url": "vaw-api-1.0.18+26.3.jar",
          "size": 55555,
          "sha512": "4571c3eca68b6820e1e9df31d52e88b9a96fb03e2182323aeccf3ee51f049602cf946f1c360aeab5161c4aff1d48d76602524121aa00da7c85542cec2b8b95ac",
          "sha256": "883e2776bdeae2781f3c47a0a93925066fadc6f7b692286352527a4e925ae8ed",
          "sha1": "fef0b1f846d528c9808d6d43a7830a47375e98d2",
          "md5": "d9df66ab9ecac39b357b0d7e91829146"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.18+26.3-sources.jar",
          "url": "vaw-api-1.0.18+26.3-sources.jar",
          "size": 43188,
          "sha512": "8fea454ca4bb5f82219404a30fd162b64bd28f69e30727939b7e1cd64eec06df0bea476dce11a826446f68cb80d37a2ac508d753547bc3929d967e5ce386221e",
          "sha256": "33ed5db5c68facd0b839010d56e257866903b1a5696cf004393d100322b58370",
          "sha1": "d518e2a88e91c9bc457f28c6ae572060d2336d14",
          "md5": "2ad4b2d2a69cf634fdc5737dbe870a4c"
        }
      ]
    }
  ]
}
