{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.1.0+26.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.1.0+26.3-SNAPSHOT.jar",
          "url": "vaw-api-0.1.0+26.3-SNAPSHOT.jar",
          "size": 10766,
          "sha512": "401a04ed291a2f2154da672c8612af867c3933ada9cbcc1a717ad7c6a88c0aa7c479101b05d5580924789b2aab26d66bd6036fe4bfec9caa272fa375634dfae0",
          "sha256": "b99c8036d0bcafe6516d593ec1b84dc96e17c34565d268e5800795aec8037e94",
          "sha1": "211fa846f68fc5649cffcb9827a179b5ac7aee09",
          "md5": "28dac830a734dbac0520380b74bcef6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.1.0+26.3-SNAPSHOT.jar",
          "url": "vaw-api-0.1.0+26.3-SNAPSHOT.jar",
          "size": 10766,
          "sha512": "401a04ed291a2f2154da672c8612af867c3933ada9cbcc1a717ad7c6a88c0aa7c479101b05d5580924789b2aab26d66bd6036fe4bfec9caa272fa375634dfae0",
          "sha256": "b99c8036d0bcafe6516d593ec1b84dc96e17c34565d268e5800795aec8037e94",
          "sha1": "211fa846f68fc5649cffcb9827a179b5ac7aee09",
          "md5": "28dac830a734dbac0520380b74bcef6f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.1.0+26.3-SNAPSHOT-sources.jar",
          "url": "vaw-api-0.1.0+26.3-SNAPSHOT-sources.jar",
          "size": 5752,
          "sha512": "c83a71c1416c37835adcb63f0295251e8541a00e7e1c4a3444733a335ffcec0a04af4cca6fff4e80ed44e3ebd6946f199b7691fc37394eedcfd0a93fefc67b6c",
          "sha256": "0433ae5f5190d97114d2ac12ebf818fe8d1c83ca66efd67ed3c40cd14ca2216c",
          "sha1": "b3b935e3afeb654e3005702ef4bb0055f348f2dc",
          "md5": "e9968e4fbb74071ac22d932ca47911e7"
        }
      ]
    }
  ]
}
