{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.6+26.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.6+26.1.2.jar",
          "url": "vaw-api-1.0.6+26.1.2.jar",
          "size": 25799,
          "sha512": "9a3e5b8081804574c642ad15a6dae082d9fa565f57fc49f9ff5c0992059fb44cdeac9e68f41c0b2b0592409a7ddcb55dc28a68f2cf35a8800834f4dc65e48c21",
          "sha256": "c9f0750cb28bc1cef9aa09c9fa5e47c6869e3409587ada0d0a4969f7b8486d10",
          "sha1": "753ec4e903a3029c4a97ef63c3bf63bad4e04d04",
          "md5": "5fd706e64ad1a82214a990b433cab359"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.6+26.1.2.jar",
          "url": "vaw-api-1.0.6+26.1.2.jar",
          "size": 25799,
          "sha512": "9a3e5b8081804574c642ad15a6dae082d9fa565f57fc49f9ff5c0992059fb44cdeac9e68f41c0b2b0592409a7ddcb55dc28a68f2cf35a8800834f4dc65e48c21",
          "sha256": "c9f0750cb28bc1cef9aa09c9fa5e47c6869e3409587ada0d0a4969f7b8486d10",
          "sha1": "753ec4e903a3029c4a97ef63c3bf63bad4e04d04",
          "md5": "5fd706e64ad1a82214a990b433cab359"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.6+26.1.2-sources.jar",
          "url": "vaw-api-1.0.6+26.1.2-sources.jar",
          "size": 14407,
          "sha512": "54b830f1ecf4ead6f129c347a57c9bd608d6b2edadb490c4212034e62c2fbaa8d86aee2a7186ee45e4d39d3b54b4a7f651dbc61a8a4d1899b6d43bdc32e81908",
          "sha256": "2be0708c0a4def6e74c1092c3e4ca5c9ae52ebec50f591d1862bec41f09acd5d",
          "sha1": "f90b5315a4ce40f435edec609b79eb784950e466",
          "md5": "67be78b9fe2ed70d424483270b2b6c5c"
        }
      ]
    }
  ]
}
