{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.8+26.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.8+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.8+26.1.2-SNAPSHOT.jar",
          "size": 26947,
          "sha512": "5591a96b4302f87530113d606431963855fc4ea514149d0dd73d60e165d402f566f35b07e0042600f23322e7c577736b3bf689d354f09ab2cc8ab5e3f52faafa",
          "sha256": "f7d3aca0a833166d3fa8586e41de179d31a1ae06a9c85f5d5cf4eda4e65af1e7",
          "sha1": "dbe4d7cd8734fba56238b533618c2066e5024a5e",
          "md5": "ec48c2bec1ba7cac7434b34c7b995471"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.8+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.8+26.1.2-SNAPSHOT.jar",
          "size": 26947,
          "sha512": "5591a96b4302f87530113d606431963855fc4ea514149d0dd73d60e165d402f566f35b07e0042600f23322e7c577736b3bf689d354f09ab2cc8ab5e3f52faafa",
          "sha256": "f7d3aca0a833166d3fa8586e41de179d31a1ae06a9c85f5d5cf4eda4e65af1e7",
          "sha1": "dbe4d7cd8734fba56238b533618c2066e5024a5e",
          "md5": "ec48c2bec1ba7cac7434b34c7b995471"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.8+26.1.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.8+26.1.2-SNAPSHOT-sources.jar",
          "size": 14619,
          "sha512": "c478c75ef63ed95fa767aa93dd61156675716e5e3267c4b2e199e9420302471db6cbc0161237202e36fb1d70d37e66bd943959f76b2073b1949555d76ba026a5",
          "sha256": "075f111e26f4b20d6bc2435a4317fc42e19a4c51245afa5a9c84a1b3204aad97",
          "sha1": "49385236b810e9d58f42c90aa5fd1deaa04278e2",
          "md5": "c964b72b42a879b9780dcc7ae10b81a4"
        }
      ]
    }
  ]
}
