{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.0+26.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.0+26.3-SNAPSHOT.jar",
          "url": "vaw-api-1.0.0+26.3-SNAPSHOT.jar",
          "size": 20096,
          "sha512": "279357d28d56c51ebe96d288e776edee41e3c91df481e69f5a1e50d210a76bc9a79921b0950e977f12e5f23beb9bb0a2c47a7cd5bf819c6fe66a70bac4650873",
          "sha256": "6149dba86b6e8c9d6b812b561218fa886cd3f30fe493c83f489dd0d964af0f8f",
          "sha1": "c2a1287ff0cb0657b848567153167d05bd81b91d",
          "md5": "73ef13251703714550b4342341f93b6d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.0+26.3-SNAPSHOT.jar",
          "url": "vaw-api-1.0.0+26.3-SNAPSHOT.jar",
          "size": 20096,
          "sha512": "279357d28d56c51ebe96d288e776edee41e3c91df481e69f5a1e50d210a76bc9a79921b0950e977f12e5f23beb9bb0a2c47a7cd5bf819c6fe66a70bac4650873",
          "sha256": "6149dba86b6e8c9d6b812b561218fa886cd3f30fe493c83f489dd0d964af0f8f",
          "sha1": "c2a1287ff0cb0657b848567153167d05bd81b91d",
          "md5": "73ef13251703714550b4342341f93b6d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.0+26.3-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.0+26.3-SNAPSHOT-sources.jar",
          "size": 11433,
          "sha512": "6e04c143450990478b1681f68949e67c58670c1b7dcb3ef90bc06ae7f4f5333180ff88830b5e1dc883999d9249297d65d75dfd61994e39b57cec5e3b8a9e88b6",
          "sha256": "3877438f5369d6b4941cd634e362804dc0310b0dc183e9b7c1b336f09575b41d",
          "sha1": "1db4168371f04303148774f9b04924990de452f1",
          "md5": "3122730f18ed1e95f85106be0d342315"
        }
      ]
    }
  ]
}
