{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.10.1+26.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.1+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-0.10.1+26.1.2-SNAPSHOT.jar",
          "size": 18476,
          "sha512": "0a88545e5c8409d6146ecaae31f26f305ed69cf60c38ca00363dfb9ccafbf8a7840163218292730d5fc33a51aecc5feb6636d67d911b6f95b2ba33c3f12faff4",
          "sha256": "9eae44804f59e1f5d9d556a3c2fc924d95d525de4f1955aeef05fde0824d1d44",
          "sha1": "f3d43c8a1d1785619316cfee5a87d055b3031e0b",
          "md5": "dd14fe0bfefea450d552085709cf535e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.1+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-0.10.1+26.1.2-SNAPSHOT.jar",
          "size": 18476,
          "sha512": "0a88545e5c8409d6146ecaae31f26f305ed69cf60c38ca00363dfb9ccafbf8a7840163218292730d5fc33a51aecc5feb6636d67d911b6f95b2ba33c3f12faff4",
          "sha256": "9eae44804f59e1f5d9d556a3c2fc924d95d525de4f1955aeef05fde0824d1d44",
          "sha1": "f3d43c8a1d1785619316cfee5a87d055b3031e0b",
          "md5": "dd14fe0bfefea450d552085709cf535e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.10.1+26.1.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-0.10.1+26.1.2-SNAPSHOT-sources.jar",
          "size": 10009,
          "sha512": "6ee8ef75c7f6b0a02149cbd17accf1b2f8bf39bcfa7e7a95670f81d440f52c5834eb35c876167cc119f65bbc45e35a9d67a41c08b598c68ca77ee547af7df0e2",
          "sha256": "637ed71da2198ae257e6e6b8d08b667ce0b747acf66ea97ed21807409002c0df",
          "sha1": "858677dea1fa876e17c4f56f8d2b1c6cde8740ca",
          "md5": "e8c522ef1820c4b06fd57a93927d71cd"
        }
      ]
    }
  ]
}
