{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.10.1+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.1+26.2.jar",
          "url": "vaw-api-0.10.1+26.2.jar",
          "size": 18465,
          "sha512": "1967ab28b0684f8d76d56937dc71ad002c606aa24c89acd630f07ef6141b608d53efd444103c75924429ae2cdde937f854788bed9cef539954a81458da5b04ea",
          "sha256": "10bccd8e9fc5a6dc31525a6ca2eaa1405cc7630fba9cd7cefd8c8e6b6d853c11",
          "sha1": "83b5b9226b3aa0d49715507c83ebd0dd8e777ba0",
          "md5": "e1e8e8bef43001dd8d4d498b2e80a18c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.1+26.2.jar",
          "url": "vaw-api-0.10.1+26.2.jar",
          "size": 18465,
          "sha512": "1967ab28b0684f8d76d56937dc71ad002c606aa24c89acd630f07ef6141b608d53efd444103c75924429ae2cdde937f854788bed9cef539954a81458da5b04ea",
          "sha256": "10bccd8e9fc5a6dc31525a6ca2eaa1405cc7630fba9cd7cefd8c8e6b6d853c11",
          "sha1": "83b5b9226b3aa0d49715507c83ebd0dd8e777ba0",
          "md5": "e1e8e8bef43001dd8d4d498b2e80a18c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.10.1+26.2-sources.jar",
          "url": "vaw-api-0.10.1+26.2-sources.jar",
          "size": 10005,
          "sha512": "eaa87e2a945fa6bfbc83d3e477f65484cbfc78ebee8488776f904dd061e522dcb310545748e994941d1e5f567769ea108300a96eedfc883ed96489b7829d2e44",
          "sha256": "03115d5d82aec252c0e494711bf5e0e712509443e039edfeeea1ab1e06ff55b7",
          "sha1": "4d9da97d1e71ee65bf0abb3ef53eca1941294393",
          "md5": "a6bea7faaf026803122c2b437975debb"
        }
      ]
    }
  ]
}
