{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.8+26.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.8+26.3.jar",
          "url": "vaw-api-1.0.8+26.3.jar",
          "size": 26936,
          "sha512": "2fbdb74129ff753f987cfc08c6d7afa9fc750839d79c165a269c8a8b63ebb54e1e616fa951992aff8663b1c245b582798ebab1d7d4aa23536403402258c7ebb1",
          "sha256": "8562cc528852d17f40cbf3b27b0ccbe0229cb82397f63b0de81b2814313723b3",
          "sha1": "7b589337b5d6359d7d47ab64301ea0caaf1a1cd4",
          "md5": "c6b74da01ebe3d3b1ecc2e9feca97a45"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.8+26.3.jar",
          "url": "vaw-api-1.0.8+26.3.jar",
          "size": 26936,
          "sha512": "2fbdb74129ff753f987cfc08c6d7afa9fc750839d79c165a269c8a8b63ebb54e1e616fa951992aff8663b1c245b582798ebab1d7d4aa23536403402258c7ebb1",
          "sha256": "8562cc528852d17f40cbf3b27b0ccbe0229cb82397f63b0de81b2814313723b3",
          "sha1": "7b589337b5d6359d7d47ab64301ea0caaf1a1cd4",
          "md5": "c6b74da01ebe3d3b1ecc2e9feca97a45"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.8+26.3-sources.jar",
          "url": "vaw-api-1.0.8+26.3-sources.jar",
          "size": 14615,
          "sha512": "ffe28966585a0476dc361a5f769a4fc87c66b84bc5c18878618cc4599aa02edb8cfe7165d98db44bce2aa5c06f7fd8fdf214499fecb5158e801f91d509a03a89",
          "sha256": "a84fa2fead9c93f1fabfb5f4f8656da3ab6b3679bba5cbecc663cb802b71ae86",
          "sha1": "888b892d9a4a4d5fc4197f5871c73ce2403d6d9d",
          "md5": "c948ae243b789f4f716a0a5cfa3265a9"
        }
      ]
    }
  ]
}
