{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.4+26.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.4+26.1.2.jar",
          "url": "vaw-api-1.0.4+26.1.2.jar",
          "size": 25799,
          "sha512": "667d4a6472a9acf540568beb4a7ed8ec6e81abdec71634cf2bb7887381a5564023027be83cd39bcbe9fffde2088ba5d790cc936f7131b4ac1b462177305c4756",
          "sha256": "eaa42843eb87d0f5318848d558c4ee4877731c7fbf5e9dd649c2d50afff9de9f",
          "sha1": "0e50d8d1cfe2d79a4076d603283a514eb1def597",
          "md5": "ceb78ab3669cda4fd449d1c411ca1e0e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.4+26.1.2.jar",
          "url": "vaw-api-1.0.4+26.1.2.jar",
          "size": 25799,
          "sha512": "667d4a6472a9acf540568beb4a7ed8ec6e81abdec71634cf2bb7887381a5564023027be83cd39bcbe9fffde2088ba5d790cc936f7131b4ac1b462177305c4756",
          "sha256": "eaa42843eb87d0f5318848d558c4ee4877731c7fbf5e9dd649c2d50afff9de9f",
          "sha1": "0e50d8d1cfe2d79a4076d603283a514eb1def597",
          "md5": "ceb78ab3669cda4fd449d1c411ca1e0e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.4+26.1.2-sources.jar",
          "url": "vaw-api-1.0.4+26.1.2-sources.jar",
          "size": 14407,
          "sha512": "54b830f1ecf4ead6f129c347a57c9bd608d6b2edadb490c4212034e62c2fbaa8d86aee2a7186ee45e4d39d3b54b4a7f651dbc61a8a4d1899b6d43bdc32e81908",
          "sha256": "2be0708c0a4def6e74c1092c3e4ca5c9ae52ebec50f591d1862bec41f09acd5d",
          "sha1": "f90b5315a4ce40f435edec609b79eb784950e466",
          "md5": "67be78b9fe2ed70d424483270b2b6c5c"
        }
      ]
    }
  ]
}
