{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.19+26.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.19+26.3-SNAPSHOT.jar",
          "url": "vaw-api-1.0.19+26.3-SNAPSHOT.jar",
          "size": 55565,
          "sha512": "71d7c3450311a229613ae518ec7728a9b40b1991b8431aad2f047908d403787376f4437767ce4c962b0fbd8767988804c001bd1fd30512428e2c3ed0585df49c",
          "sha256": "5df590b87f91e02ef9affd517253a5b4bc5938d6e981e81dbaad935bd401026b",
          "sha1": "ede91687cdd7c0f2fb12b3ff6c4ca8bcd769b074",
          "md5": "71649a7a5f822023b9c7a003e202944b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.19+26.3-SNAPSHOT.jar",
          "url": "vaw-api-1.0.19+26.3-SNAPSHOT.jar",
          "size": 55565,
          "sha512": "71d7c3450311a229613ae518ec7728a9b40b1991b8431aad2f047908d403787376f4437767ce4c962b0fbd8767988804c001bd1fd30512428e2c3ed0585df49c",
          "sha256": "5df590b87f91e02ef9affd517253a5b4bc5938d6e981e81dbaad935bd401026b",
          "sha1": "ede91687cdd7c0f2fb12b3ff6c4ca8bcd769b074",
          "md5": "71649a7a5f822023b9c7a003e202944b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.19+26.3-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.19+26.3-SNAPSHOT-sources.jar",
          "size": 43227,
          "sha512": "6c9981523fd668df52d84c17a93d28698a02745d2c9edc73d30ea7422e4e12eb9458655a925698658a2136d0b91c442de95a5dd0c6e2e29eee7699239c4ece18",
          "sha256": "d2c527fd18d796d136649d8e0ee284356d9d808315aaeb8c8156f8d17531d8cc",
          "sha1": "ada95303d91ae06be3bcd20f415621c010c83918",
          "md5": "5c4f6df39d02ea89f6844f6b58e64894"
        }
      ]
    }
  ]
}
