{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.10.3+26.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.3+26.2-SNAPSHOT.jar",
          "url": "vaw-api-0.10.3+26.2-SNAPSHOT.jar",
          "size": 18475,
          "sha512": "1e16fd2b8dcf5ed82a494f75b1e60d92b326923fcdb352fc6f3a128a08439c383af21f21806a81aed5b6d69af92aeb5e68fcac47762b067b38f3dbae2bc639e3",
          "sha256": "f6710bffacab7da697299ae4fa607b40fb9638c9950e775f8292e642eb44a7bb",
          "sha1": "f081510b23e3cc69d7788988f7d5da9a17270e11",
          "md5": "7ba42b664a2f62aeb06d77589ba7d57d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.3+26.2-SNAPSHOT.jar",
          "url": "vaw-api-0.10.3+26.2-SNAPSHOT.jar",
          "size": 18475,
          "sha512": "1e16fd2b8dcf5ed82a494f75b1e60d92b326923fcdb352fc6f3a128a08439c383af21f21806a81aed5b6d69af92aeb5e68fcac47762b067b38f3dbae2bc639e3",
          "sha256": "f6710bffacab7da697299ae4fa607b40fb9638c9950e775f8292e642eb44a7bb",
          "sha1": "f081510b23e3cc69d7788988f7d5da9a17270e11",
          "md5": "7ba42b664a2f62aeb06d77589ba7d57d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.10.3+26.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-0.10.3+26.2-SNAPSHOT-sources.jar",
          "size": 10005,
          "sha512": "eaa87e2a945fa6bfbc83d3e477f65484cbfc78ebee8488776f904dd061e522dcb310545748e994941d1e5f567769ea108300a96eedfc883ed96489b7829d2e44",
          "sha256": "03115d5d82aec252c0e494711bf5e0e712509443e039edfeeea1ab1e06ff55b7",
          "sha1": "4d9da97d1e71ee65bf0abb3ef53eca1941294393",
          "md5": "a6bea7faaf026803122c2b437975debb"
        }
      ]
    }
  ]
}
