{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.10.6+26.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.6+26.3.jar",
          "url": "vaw-api-0.10.6+26.3.jar",
          "size": 20086,
          "sha512": "5dc6b752a0a473a391b88da85b02acd5b469e3265fc5b4e55caede5f0a43eb2634cda859f53d2a1b8488706dfe1fcabf1f6abf21bf17b2c61d7c2a8188634603",
          "sha256": "e35ab7caa0597cb2b8977a7b387f058156f3f0ff9740c95a48c185597807b4b1",
          "sha1": "98b683b23d81abfe7eeb9b9929cf9112977f41d4",
          "md5": "4f47a94634c8554e5cf728abbbe80b3f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.6+26.3.jar",
          "url": "vaw-api-0.10.6+26.3.jar",
          "size": 20086,
          "sha512": "5dc6b752a0a473a391b88da85b02acd5b469e3265fc5b4e55caede5f0a43eb2634cda859f53d2a1b8488706dfe1fcabf1f6abf21bf17b2c61d7c2a8188634603",
          "sha256": "e35ab7caa0597cb2b8977a7b387f058156f3f0ff9740c95a48c185597807b4b1",
          "sha1": "98b683b23d81abfe7eeb9b9929cf9112977f41d4",
          "md5": "4f47a94634c8554e5cf728abbbe80b3f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.10.6+26.3-sources.jar",
          "url": "vaw-api-0.10.6+26.3-sources.jar",
          "size": 11433,
          "sha512": "6e04c143450990478b1681f68949e67c58670c1b7dcb3ef90bc06ae7f4f5333180ff88830b5e1dc883999d9249297d65d75dfd61994e39b57cec5e3b8a9e88b6",
          "sha256": "3877438f5369d6b4941cd634e362804dc0310b0dc183e9b7c1b336f09575b41d",
          "sha1": "1db4168371f04303148774f9b04924990de452f1",
          "md5": "3122730f18ed1e95f85106be0d342315"
        }
      ]
    }
  ]
}
