{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.14+26.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.14+26.3.jar",
          "url": "vaw-api-1.0.14+26.3.jar",
          "size": 55555,
          "sha512": "fdb4b20403b1dc8c0d673c29455ee2a5f2c1698be6e39a2d33ae064d6449736204893f7b8b3d7378c2d33241645a9ccf58e1c781a639b67f04aa9fd085b0e709",
          "sha256": "9750306ed1a7a649968c4fa47648fb41715a0ca4b40e71ea13b5039dd38cd955",
          "sha1": "6b864d22806a762d6d8f069d662977cbcf42d246",
          "md5": "0b8640020b21096f7d57f14e86bcc01b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.14+26.3.jar",
          "url": "vaw-api-1.0.14+26.3.jar",
          "size": 55555,
          "sha512": "fdb4b20403b1dc8c0d673c29455ee2a5f2c1698be6e39a2d33ae064d6449736204893f7b8b3d7378c2d33241645a9ccf58e1c781a639b67f04aa9fd085b0e709",
          "sha256": "9750306ed1a7a649968c4fa47648fb41715a0ca4b40e71ea13b5039dd38cd955",
          "sha1": "6b864d22806a762d6d8f069d662977cbcf42d246",
          "md5": "0b8640020b21096f7d57f14e86bcc01b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.14+26.3-sources.jar",
          "url": "vaw-api-1.0.14+26.3-sources.jar",
          "size": 43186,
          "sha512": "47d0037a16a5d2cc025e9e78dc12e3bdf9bf6e496519e553ecedb81049aff7ace243cb54273b2a35d6377b1c0532459e7efb4fe3fa9a621360178464f82a51d1",
          "sha256": "911f8d2a7d6b4e51aaee2a674d02f81820ed3d5939979bafa9db00b51d711623",
          "sha1": "27f9f24eb359de013ed38b4a1d1dfd71bfe45e8e",
          "md5": "9a4493a9dfa4e464a8f1bfa05e3a4645"
        }
      ]
    }
  ]
}
