{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.9.14+26.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.14+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-0.9.14+26.1.2-SNAPSHOT.jar",
          "size": 17457,
          "sha512": "cd8ff36903e3a9fb92c24975af876a350fe968ebf34703156e9ca0c363a2afa06b336a9114e546e44019d8ac108305726689e9acb4aff5e0049bb1d9d6d775c2",
          "sha256": "3fe85999b94aad86ba3722c8607b677e8dac466a96538158eec09cf98cafdbf8",
          "sha1": "18876c67cfa5e5591265bb4fd9385bb2f12eaa40",
          "md5": "23c2955cb7c22b45f9b20da757a1b321"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.14+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-0.9.14+26.1.2-SNAPSHOT.jar",
          "size": 17457,
          "sha512": "cd8ff36903e3a9fb92c24975af876a350fe968ebf34703156e9ca0c363a2afa06b336a9114e546e44019d8ac108305726689e9acb4aff5e0049bb1d9d6d775c2",
          "sha256": "3fe85999b94aad86ba3722c8607b677e8dac466a96538158eec09cf98cafdbf8",
          "sha1": "18876c67cfa5e5591265bb4fd9385bb2f12eaa40",
          "md5": "23c2955cb7c22b45f9b20da757a1b321"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.9.14+26.1.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-0.9.14+26.1.2-SNAPSHOT-sources.jar",
          "size": 9166,
          "sha512": "adfa77d9f1774993f9c7fa50f53deda68f094225e3fab839f175954f1b75dc33b8ed470e79fc565d182ceb6365f123da4a39c25e0e0b9078d3dbd6783c428fed",
          "sha256": "ef77fa3e72823f24fce0115aff4299aca3b6a7c1e7f09cc9bdcb64e9b1d408a9",
          "sha1": "8bdb35fd4da727c7d093c08ccac122bf62d862e3",
          "md5": "f3323f5382bc055875dd3845d78e7d73"
        }
      ]
    }
  ]
}
