{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.15+26.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.15+26.3.jar",
          "url": "vaw-api-1.0.15+26.3.jar",
          "size": 55553,
          "sha512": "d8b57e547ed2959259fdbb268dfbba5b1b58c84f510aeee165530158571a2ec2df302f005153ef6e935d72d44d9ef677a28e068244ade06bc5703f77e3519faa",
          "sha256": "0b0368f5dcef7000462ccb008021b411d631f090209fcc0e7dfea33a3c6b68a8",
          "sha1": "407e9477b26a23bd782f0cb086af0f17ab9085eb",
          "md5": "bb4e5e1b5393740c907a0aaa9cd5638c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.15+26.3.jar",
          "url": "vaw-api-1.0.15+26.3.jar",
          "size": 55553,
          "sha512": "d8b57e547ed2959259fdbb268dfbba5b1b58c84f510aeee165530158571a2ec2df302f005153ef6e935d72d44d9ef677a28e068244ade06bc5703f77e3519faa",
          "sha256": "0b0368f5dcef7000462ccb008021b411d631f090209fcc0e7dfea33a3c6b68a8",
          "sha1": "407e9477b26a23bd782f0cb086af0f17ab9085eb",
          "md5": "bb4e5e1b5393740c907a0aaa9cd5638c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.15+26.3-sources.jar",
          "url": "vaw-api-1.0.15+26.3-sources.jar",
          "size": 43186,
          "sha512": "47d0037a16a5d2cc025e9e78dc12e3bdf9bf6e496519e553ecedb81049aff7ace243cb54273b2a35d6377b1c0532459e7efb4fe3fa9a621360178464f82a51d1",
          "sha256": "911f8d2a7d6b4e51aaee2a674d02f81820ed3d5939979bafa9db00b51d711623",
          "sha1": "27f9f24eb359de013ed38b4a1d1dfd71bfe45e8e",
          "md5": "9a4493a9dfa4e464a8f1bfa05e3a4645"
        }
      ]
    }
  ]
}
