{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.9.6+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.6+26.2.jar",
          "url": "vaw-api-0.9.6+26.2.jar",
          "size": 16217,
          "sha512": "c7d6ad9305ac9170c63a79f05fae6fc0cc58eb20815395418f5c3bfc4a56c28d402c790cd37d1cda17435e13a1bcbc0c609d9123c70a64099b207c17df66f5e1",
          "sha256": "01dfc5c1cc8df4d2a2f0d28c89f8db4658a04f2f1229881fe7f38f3ba0de4e1b",
          "sha1": "02dc80999760841990e923316f7a54ba7abd11d3",
          "md5": "9fd7b8959fcddad80c6339a9548f3288"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.6+26.2.jar",
          "url": "vaw-api-0.9.6+26.2.jar",
          "size": 16217,
          "sha512": "c7d6ad9305ac9170c63a79f05fae6fc0cc58eb20815395418f5c3bfc4a56c28d402c790cd37d1cda17435e13a1bcbc0c609d9123c70a64099b207c17df66f5e1",
          "sha256": "01dfc5c1cc8df4d2a2f0d28c89f8db4658a04f2f1229881fe7f38f3ba0de4e1b",
          "sha1": "02dc80999760841990e923316f7a54ba7abd11d3",
          "md5": "9fd7b8959fcddad80c6339a9548f3288"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.9.6+26.2-sources.jar",
          "url": "vaw-api-0.9.6+26.2-sources.jar",
          "size": 7861,
          "sha512": "8876ea7bad3565b17e8b94b262ea3ae28a9577618e22515a17e0ea19f00f57744be243fcf63b1b7e35aaabd17d24bc0c3d14532f82e526bce7542b09e6d870a9",
          "sha256": "b4dc0b4e8017457ba9b46e9cabdffe083919c4c6c413d353c1060d905f11d151",
          "sha1": "f22ae6a343bc82220e690913a81da0fcc19cd6ba",
          "md5": "99f1d791e81dbb50573da9ccaaa3fc5a"
        }
      ]
    }
  ]
}
