{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.3+26.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.3+26.3.jar",
          "url": "vaw-api-1.0.3+26.3.jar",
          "size": 24937,
          "sha512": "9d6953b5a939d569df0d07f07ec5b819f8e687e3afc572549f2fa40b6c1c463fff99a3ebc955a6ada173566f571d5c60c802fe9e20c33616e0a098b13f84ea8e",
          "sha256": "cbeb45131635392576c5be6f187b1a336b0e04803873d0c69b6f86a93bcf9570",
          "sha1": "ba6ea0b0e77acdb5133380bda07e81e1b3bb47aa",
          "md5": "9f06cdc359acfb267715e783120a8124"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.3+26.3.jar",
          "url": "vaw-api-1.0.3+26.3.jar",
          "size": 24937,
          "sha512": "9d6953b5a939d569df0d07f07ec5b819f8e687e3afc572549f2fa40b6c1c463fff99a3ebc955a6ada173566f571d5c60c802fe9e20c33616e0a098b13f84ea8e",
          "sha256": "cbeb45131635392576c5be6f187b1a336b0e04803873d0c69b6f86a93bcf9570",
          "sha1": "ba6ea0b0e77acdb5133380bda07e81e1b3bb47aa",
          "md5": "9f06cdc359acfb267715e783120a8124"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.3+26.3-sources.jar",
          "url": "vaw-api-1.0.3+26.3-sources.jar",
          "size": 13756,
          "sha512": "a8170553e852221b02df8c7eb0df68ffd3ccc4cf9da75c2426cdcdaa2ee72a6ba5058b2db326c6d7f795b95d16d2a62cf552fb89fd50d4ea30da19b2d98b714b",
          "sha256": "f1eb72326c6f3163b5a4adcb8a7d5465908e7d9cae76523b2bfeb945b77dbcec",
          "sha1": "593b62708052853fd9d45e65cfa429129b5b0eac",
          "md5": "3c2053a9e4efdd7038b327ee6cf3679e"
        }
      ]
    }
  ]
}
