{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.0+26.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.0+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.0+26.1.2-SNAPSHOT.jar",
          "size": 20098,
          "sha512": "d4ab9e568c84d9f998b5013bb870386c1470b17a66472e0ef357b2fae75fe6d80fff872092f6f891092af3f164645939aa4dfa8a8b9c2d3853ec5f6b2f8a7202",
          "sha256": "251252ad140cd5a00ef09f5587de372663cb22acf9cf2586798e1e847ab56945",
          "sha1": "cdf320de2ab8435e6e0d3d2e0d4094a2df3862d6",
          "md5": "531611b1048d39fde05a344fad03bac5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.0+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.0+26.1.2-SNAPSHOT.jar",
          "size": 20098,
          "sha512": "d4ab9e568c84d9f998b5013bb870386c1470b17a66472e0ef357b2fae75fe6d80fff872092f6f891092af3f164645939aa4dfa8a8b9c2d3853ec5f6b2f8a7202",
          "sha256": "251252ad140cd5a00ef09f5587de372663cb22acf9cf2586798e1e847ab56945",
          "sha1": "cdf320de2ab8435e6e0d3d2e0d4094a2df3862d6",
          "md5": "531611b1048d39fde05a344fad03bac5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.0+26.1.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.0+26.1.2-SNAPSHOT-sources.jar",
          "size": 11437,
          "sha512": "233a636dda98ba30256e366f2d469a77069e3967e11f4244bbd561ad6f1c88b38e17bde8b56b27b991f1793b99813f500e52fb9c0528c35957b3128cc0d08830",
          "sha256": "94b84fd0486027755c81c4141b65d6fac9a4aaff51a9f5a30696f67dd363b2fc",
          "sha1": "3e3c75688dfe4dd2923344b5d960c712f10b976c",
          "md5": "2f4a800329c6554b984b594e4c876c40"
        }
      ]
    }
  ]
}
