{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.7+26.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.7+26.3.jar",
          "url": "vaw-api-1.0.7+26.3.jar",
          "size": 25799,
          "sha512": "dc9837c942285dcc6e073bb75fe7129a93fb9441aa506315bb75f78e2951abfd61dca91514674f9dcfbf776bc9d2ffe6742280fc5a646fb7b8f964402f1c0e09",
          "sha256": "48fa1931458a7202ee7e8c3d2a4e05a8e47e87cd438e94a7faec65bc6cddec63",
          "sha1": "5a54156938d27f5d369a7d3486266b84903a0dc6",
          "md5": "d1514e0212bfac918feedaa8f8499b84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.7+26.3.jar",
          "url": "vaw-api-1.0.7+26.3.jar",
          "size": 25799,
          "sha512": "dc9837c942285dcc6e073bb75fe7129a93fb9441aa506315bb75f78e2951abfd61dca91514674f9dcfbf776bc9d2ffe6742280fc5a646fb7b8f964402f1c0e09",
          "sha256": "48fa1931458a7202ee7e8c3d2a4e05a8e47e87cd438e94a7faec65bc6cddec63",
          "sha1": "5a54156938d27f5d369a7d3486266b84903a0dc6",
          "md5": "d1514e0212bfac918feedaa8f8499b84"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.7+26.3-sources.jar",
          "url": "vaw-api-1.0.7+26.3-sources.jar",
          "size": 14403,
          "sha512": "582f78086bd28aed386cadd9568465617e3cc11dcc155254cb81d764316e7242414d81a883db548bbcf08bd265d939959f4e91eaf8b1399e329508c21d66d483",
          "sha256": "cd8b323a4c57a548c14cdb1cd4b55cefa1c26e004de5a4b43cff33d8f0e33422",
          "sha1": "6c9e7c6c1f927ea37cb274f9372a6f1414b2c84e",
          "md5": "59d4f590b22eb7398d34c5bf753d0871"
        }
      ]
    }
  ]
}
