{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.9.12+26.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.12+26.3.jar",
          "url": "vaw-api-0.9.12+26.3.jar",
          "size": 16362,
          "sha512": "2a757f9b560cc06db790cae9eca46a69eaaf15e2954ed2ae5d88f8ffaefb425e5e754150b1477518be9d92f7b08e447ba216a3cef5abf81b89598a3c079ede9d",
          "sha256": "e40e7307c1fa2290d90412b92e7bfaf0c125ff072fe67cf47a30c827755fb998",
          "sha1": "8607d32c352b1a3aa88b4e04188acd77ca81e968",
          "md5": "afc34bb0a184eb0767a03208b0b8d37e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.12+26.3.jar",
          "url": "vaw-api-0.9.12+26.3.jar",
          "size": 16362,
          "sha512": "2a757f9b560cc06db790cae9eca46a69eaaf15e2954ed2ae5d88f8ffaefb425e5e754150b1477518be9d92f7b08e447ba216a3cef5abf81b89598a3c079ede9d",
          "sha256": "e40e7307c1fa2290d90412b92e7bfaf0c125ff072fe67cf47a30c827755fb998",
          "sha1": "8607d32c352b1a3aa88b4e04188acd77ca81e968",
          "md5": "afc34bb0a184eb0767a03208b0b8d37e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.9.12+26.3-sources.jar",
          "url": "vaw-api-0.9.12+26.3-sources.jar",
          "size": 8055,
          "sha512": "425b17479d8cfc53de33b75e6eed7b4e4103f8da7230e1694455c936dd9549d574a8bd2303ca4e0d08d9669f37873e9087c10e61d6d2e03da4fe7f88f45e32af",
          "sha256": "647bf25689e6e127f4d2652e83ff7bf4f0df8c0f0858c01a40230372f2a5e7e2",
          "sha1": "c76d2f0b5f658018d1adedd6f7daeeb0c8be7d48",
          "md5": "cd85eea033f281f005bc9d484b023379"
        }
      ]
    }
  ]
}
