{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.10+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.10+26.2.jar",
          "url": "vaw-api-1.0.10+26.2.jar",
          "size": 26934,
          "sha512": "c0824228bf28e8e7f4f498f0dcb6dc779a37cd419d40825fbf67b22a67b3a94ccc365d67424380832b6197fec490d75a993cafe6ef318a7c1bb13df864b5309c",
          "sha256": "1d4916060047566ab0a7332e63abfb0fae0215617e759f4cdd62a7ea7b7829e1",
          "sha1": "f2b6f85e5bdc25abc808abccc49b114d24daf18a",
          "md5": "33e5f4c7a8505851be6ed67ee7b0491b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.10+26.2.jar",
          "url": "vaw-api-1.0.10+26.2.jar",
          "size": 26934,
          "sha512": "c0824228bf28e8e7f4f498f0dcb6dc779a37cd419d40825fbf67b22a67b3a94ccc365d67424380832b6197fec490d75a993cafe6ef318a7c1bb13df864b5309c",
          "sha256": "1d4916060047566ab0a7332e63abfb0fae0215617e759f4cdd62a7ea7b7829e1",
          "sha1": "f2b6f85e5bdc25abc808abccc49b114d24daf18a",
          "md5": "33e5f4c7a8505851be6ed67ee7b0491b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.10+26.2-sources.jar",
          "url": "vaw-api-1.0.10+26.2-sources.jar",
          "size": 14615,
          "sha512": "672a54df014af689d3370ad647ffc802dfca614fb8f4b66a2567dec076d97bfdf2d36102d3b7d82b452f88804f5f76f547323768b5ffe229bcf476074ffaccb8",
          "sha256": "85f7da72e1b90b56676092dd1a1985741dd547944cd2cb56f1f265428f396c3a",
          "sha1": "b283e2e049cdd100e42b041c6d7a5b2b3bd27e4a",
          "md5": "3504a1b08060783a4cc98c70b8e575b6"
        }
      ]
    }
  ]
}
