{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.14+26.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.14+26.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.14+26.2-SNAPSHOT.jar",
          "size": 55563,
          "sha512": "8f49c3bccf3d7ef1171233344e5e553ad6b75803d7ff1a2b0989098717dcad4cf922afbab5a2ae3306ed4bb9209a095aba1c9f5326a1469dc8803844d2ead990",
          "sha256": "d737a998aff3845089a7a0634eae7b668630a96363eadd36287a5117137edff0",
          "sha1": "55b0b23f37e12a46559c56698952681846b13269",
          "md5": "8cff1d59e8d5f1fa136a5c710c0a4e1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.14+26.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.14+26.2-SNAPSHOT.jar",
          "size": 55563,
          "sha512": "8f49c3bccf3d7ef1171233344e5e553ad6b75803d7ff1a2b0989098717dcad4cf922afbab5a2ae3306ed4bb9209a095aba1c9f5326a1469dc8803844d2ead990",
          "sha256": "d737a998aff3845089a7a0634eae7b668630a96363eadd36287a5117137edff0",
          "sha1": "55b0b23f37e12a46559c56698952681846b13269",
          "md5": "8cff1d59e8d5f1fa136a5c710c0a4e1e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.14+26.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.14+26.2-SNAPSHOT-sources.jar",
          "size": 43186,
          "sha512": "fc05fab289896119dd70f145255465c945e850c609ce01ea9c1479e57100adaf09701bcf2866230f7c694744b9290e0af1cf939c288100fcb25e2e92822b9a41",
          "sha256": "659fc1a5046e0b6e710fab6c08b491dfccd56204cba6d7294c12f6da7a1f704d",
          "sha1": "7162ad34c9e168b021513b16487b605b02c7bf94",
          "md5": "0d1b0d874e00c0f7be99a0344404433f"
        }
      ]
    }
  ]
}
