{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.14+26.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.14+26.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.14+26.2-SNAPSHOT.jar",
          "size": 26945,
          "sha512": "7ca34b60b067256b54154f9d4ac9c772421549ccfd87e92698ed8dce224bcb87efeaade7b38248dd87e7f05ab31d7f89447b9f8821ae39f7a58a1dd6fd7942a6",
          "sha256": "8b87cba0fef4a4f977695df34bd24fd1b9a0adf6fa0fb06ea41a666666a55c2a",
          "sha1": "1320454816dff65825c082bb430182f7a19c97ff",
          "md5": "cdb618409bf9bb0ca7142095afca165e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.14+26.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.14+26.2-SNAPSHOT.jar",
          "size": 26945,
          "sha512": "7ca34b60b067256b54154f9d4ac9c772421549ccfd87e92698ed8dce224bcb87efeaade7b38248dd87e7f05ab31d7f89447b9f8821ae39f7a58a1dd6fd7942a6",
          "sha256": "8b87cba0fef4a4f977695df34bd24fd1b9a0adf6fa0fb06ea41a666666a55c2a",
          "sha1": "1320454816dff65825c082bb430182f7a19c97ff",
          "md5": "cdb618409bf9bb0ca7142095afca165e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.14+26.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.14+26.2-SNAPSHOT-sources.jar",
          "size": 14615,
          "sha512": "672a54df014af689d3370ad647ffc802dfca614fb8f4b66a2567dec076d97bfdf2d36102d3b7d82b452f88804f5f76f547323768b5ffe229bcf476074ffaccb8",
          "sha256": "85f7da72e1b90b56676092dd1a1985741dd547944cd2cb56f1f265428f396c3a",
          "sha1": "b283e2e049cdd100e42b041c6d7a5b2b3bd27e4a",
          "md5": "3504a1b08060783a4cc98c70b8e575b6"
        }
      ]
    }
  ]
}
