{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.9.10+26.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.10+26.3.jar",
          "url": "vaw-api-0.9.10+26.3.jar",
          "size": 16218,
          "sha512": "b9fb4da1c494665da8e1173f70ce4f9b677bace6d5e31555d22dc5b70bcd66e0eb2e61de9dd28086c22fe8e7b4276ecb23e8dc02aff5b3576c073711164aecd9",
          "sha256": "a3326c799788025cd521c240a84827e1cecff5e645eec3501ceddff8e793f0c4",
          "sha1": "5d1b9236df9e6a8d603316c32a38b2bbae2d748a",
          "md5": "14b96b378a2818a27e072b0fdc4d6fe8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.10+26.3.jar",
          "url": "vaw-api-0.9.10+26.3.jar",
          "size": 16218,
          "sha512": "b9fb4da1c494665da8e1173f70ce4f9b677bace6d5e31555d22dc5b70bcd66e0eb2e61de9dd28086c22fe8e7b4276ecb23e8dc02aff5b3576c073711164aecd9",
          "sha256": "a3326c799788025cd521c240a84827e1cecff5e645eec3501ceddff8e793f0c4",
          "sha1": "5d1b9236df9e6a8d603316c32a38b2bbae2d748a",
          "md5": "14b96b378a2818a27e072b0fdc4d6fe8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.9.10+26.3-sources.jar",
          "url": "vaw-api-0.9.10+26.3-sources.jar",
          "size": 7861,
          "sha512": "496306528cb7d459ae5c54df4fab63c50315dfab8df3f96a43f6bbf615621fca5ddad4b2ea44d0bf56378eb5393a132b19c9d8ceaae4c6018b559d7fd2ede201",
          "sha256": "ff6a879b8049504bd1ba1eb99e01c926eea3ef9c5add0ac2a6781cd658ebdfc6",
          "sha1": "3d289c41b1af11e269338cadbe310e255184f63e",
          "md5": "ac0dea5b3484c057b2ac12457bd15101"
        }
      ]
    }
  ]
}
