{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.10.7+26.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.7+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-0.10.7+26.1.2-SNAPSHOT.jar",
          "size": 20099,
          "sha512": "e762b6e704c236cc8c059df86af4c050f2ca0e53f6191e449af010d2c3aeeb057a8748041351baa77aab9c085041fb6bf79d63b65184bce95c0620d728a8d109",
          "sha256": "c3e7e0a69656722e8ec7f3752f2104b195efb682e8c4864bfd421330f3be8a45",
          "sha1": "78e301af031e8f67601a1bc8df0446b2f92e07d8",
          "md5": "ddeab4568160c0697a6167d418d875bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.7+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-0.10.7+26.1.2-SNAPSHOT.jar",
          "size": 20099,
          "sha512": "e762b6e704c236cc8c059df86af4c050f2ca0e53f6191e449af010d2c3aeeb057a8748041351baa77aab9c085041fb6bf79d63b65184bce95c0620d728a8d109",
          "sha256": "c3e7e0a69656722e8ec7f3752f2104b195efb682e8c4864bfd421330f3be8a45",
          "sha1": "78e301af031e8f67601a1bc8df0446b2f92e07d8",
          "md5": "ddeab4568160c0697a6167d418d875bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.10.7+26.1.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-0.10.7+26.1.2-SNAPSHOT-sources.jar",
          "size": 11437,
          "sha512": "233a636dda98ba30256e366f2d469a77069e3967e11f4244bbd561ad6f1c88b38e17bde8b56b27b991f1793b99813f500e52fb9c0528c35957b3128cc0d08830",
          "sha256": "94b84fd0486027755c81c4141b65d6fac9a4aaff51a9f5a30696f67dd363b2fc",
          "sha1": "3e3c75688dfe4dd2923344b5d960c712f10b976c",
          "md5": "2f4a800329c6554b984b594e4c876c40"
        }
      ]
    }
  ]
}
