{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.8+26.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.8+26.3-SNAPSHOT.jar",
          "url": "vaw-api-1.0.8+26.3-SNAPSHOT.jar",
          "size": 26945,
          "sha512": "e1994d8cd84c60fb0bc3aee57bd903cbafdbcf0839cde3759929f0246ef9257e34d9972eb60f10f71fe9d2c5fb47d69a06d167fbf8032b4239791671bed8be9a",
          "sha256": "cb9a38d8c6e9bc3eccad5f7af38951a076a2d88988f22526a52b1491e06afa43",
          "sha1": "83a65951979b0e6b605905ed9a355dee9b38d95f",
          "md5": "c26930010a6dd89dd5b41002d2bbf538"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.8+26.3-SNAPSHOT.jar",
          "url": "vaw-api-1.0.8+26.3-SNAPSHOT.jar",
          "size": 26945,
          "sha512": "e1994d8cd84c60fb0bc3aee57bd903cbafdbcf0839cde3759929f0246ef9257e34d9972eb60f10f71fe9d2c5fb47d69a06d167fbf8032b4239791671bed8be9a",
          "sha256": "cb9a38d8c6e9bc3eccad5f7af38951a076a2d88988f22526a52b1491e06afa43",
          "sha1": "83a65951979b0e6b605905ed9a355dee9b38d95f",
          "md5": "c26930010a6dd89dd5b41002d2bbf538"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.8+26.3-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.8+26.3-SNAPSHOT-sources.jar",
          "size": 14615,
          "sha512": "ffe28966585a0476dc361a5f769a4fc87c66b84bc5c18878618cc4599aa02edb8cfe7165d98db44bce2aa5c06f7fd8fdf214499fecb5158e801f91d509a03a89",
          "sha256": "a84fa2fead9c93f1fabfb5f4f8656da3ab6b3679bba5cbecc663cb802b71ae86",
          "sha1": "888b892d9a4a4d5fc4197f5871c73ce2403d6d9d",
          "md5": "c948ae243b789f4f716a0a5cfa3265a9"
        }
      ]
    }
  ]
}
