{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.8+26.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.8+26.3-SNAPSHOT.jar",
          "url": "vaw-api-1.0.8+26.3-SNAPSHOT.jar",
          "size": 25808,
          "sha512": "42f2a846a2e1e8547fd359d6a2f850d56d0800b07f8f6e3acb180526e027a87b17fe999ae36b63b9de57dcf22c9f75949651ab49d03abd1c967bcca91e27c89c",
          "sha256": "84abf487a6e112ab5c44ebfcb9b3e61c6676084859a3fa25b74fc65d0ffdb614",
          "sha1": "ccdb96e3e5340847939b24ac364f84a2e209c460",
          "md5": "576cdf6640cfa3ea5efa31658f10a034"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.8+26.3-SNAPSHOT.jar",
          "url": "vaw-api-1.0.8+26.3-SNAPSHOT.jar",
          "size": 25808,
          "sha512": "42f2a846a2e1e8547fd359d6a2f850d56d0800b07f8f6e3acb180526e027a87b17fe999ae36b63b9de57dcf22c9f75949651ab49d03abd1c967bcca91e27c89c",
          "sha256": "84abf487a6e112ab5c44ebfcb9b3e61c6676084859a3fa25b74fc65d0ffdb614",
          "sha1": "ccdb96e3e5340847939b24ac364f84a2e209c460",
          "md5": "576cdf6640cfa3ea5efa31658f10a034"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.8+26.3-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.8+26.3-SNAPSHOT-sources.jar",
          "size": 14403,
          "sha512": "582f78086bd28aed386cadd9568465617e3cc11dcc155254cb81d764316e7242414d81a883db548bbcf08bd265d939959f4e91eaf8b1399e329508c21d66d483",
          "sha256": "cd8b323a4c57a548c14cdb1cd4b55cefa1c26e004de5a4b43cff33d8f0e33422",
          "sha1": "6c9e7c6c1f927ea37cb274f9372a6f1414b2c84e",
          "md5": "59d4f590b22eb7398d34c5bf753d0871"
        }
      ]
    }
  ]
}
