{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.4+26.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.4+26.3-SNAPSHOT.jar",
          "url": "vaw-api-1.0.4+26.3-SNAPSHOT.jar",
          "size": 24945,
          "sha512": "9be8d2dbf72bfb6a62612e2e6fddd1b6ddf55d6148096fdaf7e756f5ecf90aa812d129bc811928ec30b2a2c0cc52f4d8b30fcda32290658463466cb00c8aba21",
          "sha256": "88dc019fb778ba65ca6cd7ec4c762a47ff513efb2c8d6fa24ccd826969406fbb",
          "sha1": "79a2ffc13e8c8214c03200abf6814fc4af26157c",
          "md5": "e48debfa3ea18138f36807f1d638b607"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.4+26.3-SNAPSHOT.jar",
          "url": "vaw-api-1.0.4+26.3-SNAPSHOT.jar",
          "size": 24945,
          "sha512": "9be8d2dbf72bfb6a62612e2e6fddd1b6ddf55d6148096fdaf7e756f5ecf90aa812d129bc811928ec30b2a2c0cc52f4d8b30fcda32290658463466cb00c8aba21",
          "sha256": "88dc019fb778ba65ca6cd7ec4c762a47ff513efb2c8d6fa24ccd826969406fbb",
          "sha1": "79a2ffc13e8c8214c03200abf6814fc4af26157c",
          "md5": "e48debfa3ea18138f36807f1d638b607"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.4+26.3-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.4+26.3-SNAPSHOT-sources.jar",
          "size": 13756,
          "sha512": "a8170553e852221b02df8c7eb0df68ffd3ccc4cf9da75c2426cdcdaa2ee72a6ba5058b2db326c6d7f795b95d16d2a62cf552fb89fd50d4ea30da19b2d98b714b",
          "sha256": "f1eb72326c6f3163b5a4adcb8a7d5465908e7d9cae76523b2bfeb945b77dbcec",
          "sha1": "593b62708052853fd9d45e65cfa429129b5b0eac",
          "md5": "3c2053a9e4efdd7038b327ee6cf3679e"
        }
      ]
    }
  ]
}
