{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.9.12+26.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.12+26.3-SNAPSHOT.jar",
          "url": "vaw-api-0.9.12+26.3-SNAPSHOT.jar",
          "size": 16227,
          "sha512": "c5932ac932fcf5224b2df8485aaf0c038c87b2af561216865fa67ea1c2d47ce2a8d573745ad6e71c307084826b8f0db0b3f23bb84543077df6aa7a87be9b5ccf",
          "sha256": "0033d900f780b098f588427ec83bcfadd47035d60f2bb5c5866329a0dca28402",
          "sha1": "b42ce02d3d6184a0d7d1419ec79fadc28247d4e7",
          "md5": "ca712d2d39061c19a24ffd8bf58521e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.12+26.3-SNAPSHOT.jar",
          "url": "vaw-api-0.9.12+26.3-SNAPSHOT.jar",
          "size": 16227,
          "sha512": "c5932ac932fcf5224b2df8485aaf0c038c87b2af561216865fa67ea1c2d47ce2a8d573745ad6e71c307084826b8f0db0b3f23bb84543077df6aa7a87be9b5ccf",
          "sha256": "0033d900f780b098f588427ec83bcfadd47035d60f2bb5c5866329a0dca28402",
          "sha1": "b42ce02d3d6184a0d7d1419ec79fadc28247d4e7",
          "md5": "ca712d2d39061c19a24ffd8bf58521e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.9.12+26.3-SNAPSHOT-sources.jar",
          "url": "vaw-api-0.9.12+26.3-SNAPSHOT-sources.jar",
          "size": 7861,
          "sha512": "496306528cb7d459ae5c54df4fab63c50315dfab8df3f96a43f6bbf615621fca5ddad4b2ea44d0bf56378eb5393a132b19c9d8ceaae4c6018b559d7fd2ede201",
          "sha256": "ff6a879b8049504bd1ba1eb99e01c926eea3ef9c5add0ac2a6781cd658ebdfc6",
          "sha1": "3d289c41b1af11e269338cadbe310e255184f63e",
          "md5": "ac0dea5b3484c057b2ac12457bd15101"
        }
      ]
    }
  ]
}
