{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.9+26.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.9+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.9+26.1.2-SNAPSHOT.jar",
          "size": 26947,
          "sha512": "6b3f3821e61ea80b7d908639c3e0c18a9477459c798d159bd30cc7b040a7c572cc39944c2ff9af54d61d1e3d674183edf0cf92c6c651ae42428e93a3437ab99b",
          "sha256": "068e354dca4b31d5c92202e2e1a800f80ea38451c2604b4b48fd7b7862084724",
          "sha1": "74d76fafe9aaade01bbb878432a6b215adbe45cb",
          "md5": "e20f058adaf40c347c36154668bd2c2d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.9+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.9+26.1.2-SNAPSHOT.jar",
          "size": 26947,
          "sha512": "6b3f3821e61ea80b7d908639c3e0c18a9477459c798d159bd30cc7b040a7c572cc39944c2ff9af54d61d1e3d674183edf0cf92c6c651ae42428e93a3437ab99b",
          "sha256": "068e354dca4b31d5c92202e2e1a800f80ea38451c2604b4b48fd7b7862084724",
          "sha1": "74d76fafe9aaade01bbb878432a6b215adbe45cb",
          "md5": "e20f058adaf40c347c36154668bd2c2d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.9+26.1.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.9+26.1.2-SNAPSHOT-sources.jar",
          "size": 14619,
          "sha512": "c478c75ef63ed95fa767aa93dd61156675716e5e3267c4b2e199e9420302471db6cbc0161237202e36fb1d70d37e66bd943959f76b2073b1949555d76ba026a5",
          "sha256": "075f111e26f4b20d6bc2435a4317fc42e19a4c51245afa5a9c84a1b3204aad97",
          "sha1": "49385236b810e9d58f42c90aa5fd1deaa04278e2",
          "md5": "c964b72b42a879b9780dcc7ae10b81a4"
        }
      ]
    }
  ]
}
