{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.1+26.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.1+26.1.2.jar",
          "url": "vaw-api-1.0.1+26.1.2.jar",
          "size": 24935,
          "sha512": "1e232392bd855d1be85088c31e46e11af6ac2caa332f172d0db6c864681939573f66ce77868f74cbbe0d51a38db14292fbd7079cae8d38539ff6a47d2f37921c",
          "sha256": "7d1f96d4972a4730900c4042a48c8d5ae28a35125b4db0f0ecf89ff6969927ce",
          "sha1": "dcc5a2d76f2f482d69d556b145f45ece4347b1e4",
          "md5": "625adfffe2180849fdf08e6f25264c02"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.1+26.1.2.jar",
          "url": "vaw-api-1.0.1+26.1.2.jar",
          "size": 24935,
          "sha512": "1e232392bd855d1be85088c31e46e11af6ac2caa332f172d0db6c864681939573f66ce77868f74cbbe0d51a38db14292fbd7079cae8d38539ff6a47d2f37921c",
          "sha256": "7d1f96d4972a4730900c4042a48c8d5ae28a35125b4db0f0ecf89ff6969927ce",
          "sha1": "dcc5a2d76f2f482d69d556b145f45ece4347b1e4",
          "md5": "625adfffe2180849fdf08e6f25264c02"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.1+26.1.2-sources.jar",
          "url": "vaw-api-1.0.1+26.1.2-sources.jar",
          "size": 13760,
          "sha512": "1880ddb8a90abed87a14417d5f81ab0cd761f734baaf0bd5c15a9b54e265a0421cf3cbba535693a86e3dcc470a94364736e073858b4d3734ce2f62f769671960",
          "sha256": "44abdb4ce4559f3af731665580bd39e946094eddb18bd1643b364f9474c6881d",
          "sha1": "e876d49bcb44c8f886320f7de799393c7e321015",
          "md5": "d145c6fda67a0201c69d7c9d1ca4299a"
        }
      ]
    }
  ]
}
