{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.17+26.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.17+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.17+26.1.2-SNAPSHOT.jar",
          "size": 55570,
          "sha512": "61d6c7c959bec4ce4b0e1cc0458cd060a735aba45cd235214ebe45a2fafcf1f5a02bd7d5413adf942e3e00f7e47f9486f84c407d02092450e7e02c7bc5d41d50",
          "sha256": "ae743f4137bdfbc6023b750c99d50499745a596588f11a4358e02cf37dbb63e4",
          "sha1": "bd6f0fbecf18c0e731118562a62e6869d691f55e",
          "md5": "7e15b23bd8c8ac0293fd0726cdc0da9f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.17+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-1.0.17+26.1.2-SNAPSHOT.jar",
          "size": 55570,
          "sha512": "61d6c7c959bec4ce4b0e1cc0458cd060a735aba45cd235214ebe45a2fafcf1f5a02bd7d5413adf942e3e00f7e47f9486f84c407d02092450e7e02c7bc5d41d50",
          "sha256": "ae743f4137bdfbc6023b750c99d50499745a596588f11a4358e02cf37dbb63e4",
          "sha1": "bd6f0fbecf18c0e731118562a62e6869d691f55e",
          "md5": "7e15b23bd8c8ac0293fd0726cdc0da9f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.17+26.1.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.17+26.1.2-SNAPSHOT-sources.jar",
          "size": 43192,
          "sha512": "d084df9523c2281a50a054db05c8139cfe8f13badfb2afefb73259d08849ad192c4534b9de8a6a20187f269364f6a7b379d659d69d2a542d34bc589a4ab495bd",
          "sha256": "4c886a22b960329fb06a3798c528dff3aab85b0f5cb4c5bf4d1ed70bc77dba4d",
          "sha1": "35934e0f16c10c4b798669905f22ea32d352d59f",
          "md5": "a6202748b342579805cc5a9e48b62f78"
        }
      ]
    }
  ]
}
