{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.9.4+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.4+26.2.jar",
          "url": "vaw-api-0.9.4+26.2.jar",
          "size": 16217,
          "sha512": "3c2ab615ccf363f434d916dabd044bc083979f654029e609be557ac03b2737707da3bef00d93d9fb0062f74bf96af0dd1a196f01b63c96ce9f990b866f2c13ee",
          "sha256": "c30ed55925b22f7e7ef54cb5cb2af68355e4cd1ff1dac3c6252a5797c8e570bb",
          "sha1": "9338d524ca27bdd562a7a61bf78cf8dac273d55e",
          "md5": "3a743f42b8914bd58aa70df03427f03e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.0+26.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.4+26.2.jar",
          "url": "vaw-api-0.9.4+26.2.jar",
          "size": 16217,
          "sha512": "3c2ab615ccf363f434d916dabd044bc083979f654029e609be557ac03b2737707da3bef00d93d9fb0062f74bf96af0dd1a196f01b63c96ce9f990b866f2c13ee",
          "sha256": "c30ed55925b22f7e7ef54cb5cb2af68355e4cd1ff1dac3c6252a5797c8e570bb",
          "sha1": "9338d524ca27bdd562a7a61bf78cf8dac273d55e",
          "md5": "3a743f42b8914bd58aa70df03427f03e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.9.4+26.2-sources.jar",
          "url": "vaw-api-0.9.4+26.2-sources.jar",
          "size": 7861,
          "sha512": "8876ea7bad3565b17e8b94b262ea3ae28a9577618e22515a17e0ea19f00f57744be243fcf63b1b7e35aaabd17d24bc0c3d14532f82e526bce7542b09e6d870a9",
          "sha256": "b4dc0b4e8017457ba9b46e9cabdffe083919c4c6c413d353c1060d905f11d151",
          "sha1": "f22ae6a343bc82220e690913a81da0fcc19cd6ba",
          "md5": "99f1d791e81dbb50573da9ccaaa3fc5a"
        }
      ]
    }
  ]
}
