{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.12+26.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.12+26.1.2.jar",
          "url": "vaw-api-1.0.12+26.1.2.jar",
          "size": 26936,
          "sha512": "b62de3b8b3ed22f9e269317a2a9dbe5e770cce5a9a111d95d5350bdc549571dbeb2b8ff09c8543b73dd028f16d8433e669ba59e51bb2ac15c4c177a8650cf3ff",
          "sha256": "9c4cf68dc6c693a3f3e93cad5555c0d8c8686431d767d04e8614c892f6ecfcb4",
          "sha1": "45ce30434aa1db297220b75875609326b7478a99",
          "md5": "4a514bf9264c73cb6ea37841846d87b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.12+26.1.2.jar",
          "url": "vaw-api-1.0.12+26.1.2.jar",
          "size": 26936,
          "sha512": "b62de3b8b3ed22f9e269317a2a9dbe5e770cce5a9a111d95d5350bdc549571dbeb2b8ff09c8543b73dd028f16d8433e669ba59e51bb2ac15c4c177a8650cf3ff",
          "sha256": "9c4cf68dc6c693a3f3e93cad5555c0d8c8686431d767d04e8614c892f6ecfcb4",
          "sha1": "45ce30434aa1db297220b75875609326b7478a99",
          "md5": "4a514bf9264c73cb6ea37841846d87b6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.12+26.1.2-sources.jar",
          "url": "vaw-api-1.0.12+26.1.2-sources.jar",
          "size": 14619,
          "sha512": "c478c75ef63ed95fa767aa93dd61156675716e5e3267c4b2e199e9420302471db6cbc0161237202e36fb1d70d37e66bd943959f76b2073b1949555d76ba026a5",
          "sha256": "075f111e26f4b20d6bc2435a4317fc42e19a4c51245afa5a9c84a1b3204aad97",
          "sha1": "49385236b810e9d58f42c90aa5fd1deaa04278e2",
          "md5": "c964b72b42a879b9780dcc7ae10b81a4"
        }
      ]
    }
  ]
}
