{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.9.2+26.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.2+26.3-SNAPSHOT.jar",
          "url": "vaw-api-0.9.2+26.3-SNAPSHOT.jar",
          "size": 16226,
          "sha512": "84098be955ba2e805957febea37d2933562c3f56f688c7aed292bffcf384074bf5d2023d3a8d9f243082f63a91d72631753dc530d7e72d0419a2927cc2acd05a",
          "sha256": "26977a242a734705cd787679f09f8fba6083c5b5b435001ed035bad93aac0232",
          "sha1": "6f7ef883d92d71129f63dae93c506cabdc60b10a",
          "md5": "c70ded44eb80dc423d04be4d0d82c11b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.9.2+26.3-SNAPSHOT.jar",
          "url": "vaw-api-0.9.2+26.3-SNAPSHOT.jar",
          "size": 16226,
          "sha512": "84098be955ba2e805957febea37d2933562c3f56f688c7aed292bffcf384074bf5d2023d3a8d9f243082f63a91d72631753dc530d7e72d0419a2927cc2acd05a",
          "sha256": "26977a242a734705cd787679f09f8fba6083c5b5b435001ed035bad93aac0232",
          "sha1": "6f7ef883d92d71129f63dae93c506cabdc60b10a",
          "md5": "c70ded44eb80dc423d04be4d0d82c11b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.9.2+26.3-SNAPSHOT-sources.jar",
          "url": "vaw-api-0.9.2+26.3-SNAPSHOT-sources.jar",
          "size": 7861,
          "sha512": "496306528cb7d459ae5c54df4fab63c50315dfab8df3f96a43f6bbf615621fca5ddad4b2ea44d0bf56378eb5393a132b19c9d8ceaae4c6018b559d7fd2ede201",
          "sha256": "ff6a879b8049504bd1ba1eb99e01c926eea3ef9c5add0ac2a6781cd658ebdfc6",
          "sha1": "3d289c41b1af11e269338cadbe310e255184f63e",
          "md5": "ac0dea5b3484c057b2ac12457bd15101"
        }
      ]
    }
  ]
}
