{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "1.0.10+26.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.10+26.3-SNAPSHOT.jar",
          "url": "vaw-api-1.0.10+26.3-SNAPSHOT.jar",
          "size": 26945,
          "sha512": "ab1ac768bc19e56706ac61913245ea6c6772c67306916168ea54cfd35596f7c0aa5e82231dcffd577c01b8c69ae149b4d0bdeb61176a6accde7ce958f47eb866",
          "sha256": "2b78609508b8abdb0d81108e1c471bb3a6ab828072bafcf5d5c34eebc7d05dbe",
          "sha1": "d675c1fd81837d7811cc89882aff32f7e5c80e93",
          "md5": "3a9ebcab3e497c97b4078aaa34c2b429"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.160.5+26.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-1.0.10+26.3-SNAPSHOT.jar",
          "url": "vaw-api-1.0.10+26.3-SNAPSHOT.jar",
          "size": 26945,
          "sha512": "ab1ac768bc19e56706ac61913245ea6c6772c67306916168ea54cfd35596f7c0aa5e82231dcffd577c01b8c69ae149b4d0bdeb61176a6accde7ce958f47eb866",
          "sha256": "2b78609508b8abdb0d81108e1c471bb3a6ab828072bafcf5d5c34eebc7d05dbe",
          "sha1": "d675c1fd81837d7811cc89882aff32f7e5c80e93",
          "md5": "3a9ebcab3e497c97b4078aaa34c2b429"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-1.0.10+26.3-SNAPSHOT-sources.jar",
          "url": "vaw-api-1.0.10+26.3-SNAPSHOT-sources.jar",
          "size": 14615,
          "sha512": "ffe28966585a0476dc361a5f769a4fc87c66b84bc5c18878618cc4599aa02edb8cfe7165d98db44bce2aa5c06f7fd8fdf214499fecb5158e801f91d509a03a89",
          "sha256": "a84fa2fead9c93f1fabfb5f4f8656da3ab6b3679bba5cbecc663cb802b71ae86",
          "sha1": "888b892d9a4a4d5fc4197f5871c73ce2403d6d9d",
          "md5": "c948ae243b789f4f716a0a5cfa3265a9"
        }
      ]
    }
  ]
}
