{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.msameer.vaw",
    "module": "vaw-api",
    "version": "0.10.2+26.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.2+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-0.10.2+26.1.2-SNAPSHOT.jar",
          "size": 18477,
          "sha512": "4475eaee79f84e754012fb50ff334c2a0b368fe7e40200966219dfb4bc9353e1ac0664c3bb127ef6070e12cba6e1b7e8525107fd3b050f2031f537c2618df0f3",
          "sha256": "2c7b693c1456d6985faa2f2f85072882c4a2de53844132feed68336470b755ed",
          "sha1": "7ea796aac09951cd2b3bf154bd8394babf2f9b6d",
          "md5": "2655fe57ee15be52171e414962fc1cda"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.3+26.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-language-kotlin",
          "version": {
            "requires": "1.14.1+kotlin.2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "vaw-api-0.10.2+26.1.2-SNAPSHOT.jar",
          "url": "vaw-api-0.10.2+26.1.2-SNAPSHOT.jar",
          "size": 18477,
          "sha512": "4475eaee79f84e754012fb50ff334c2a0b368fe7e40200966219dfb4bc9353e1ac0664c3bb127ef6070e12cba6e1b7e8525107fd3b050f2031f537c2618df0f3",
          "sha256": "2c7b693c1456d6985faa2f2f85072882c4a2de53844132feed68336470b755ed",
          "sha1": "7ea796aac09951cd2b3bf154bd8394babf2f9b6d",
          "md5": "2655fe57ee15be52171e414962fc1cda"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vaw-api-0.10.2+26.1.2-SNAPSHOT-sources.jar",
          "url": "vaw-api-0.10.2+26.1.2-SNAPSHOT-sources.jar",
          "size": 10009,
          "sha512": "6ee8ef75c7f6b0a02149cbd17accf1b2f8bf39bcfa7e7a95670f81d440f52c5834eb35c876167cc119f65bbc45e35a9d67a41c08b598c68ca77ee547af7df0e2",
          "sha256": "637ed71da2198ae257e6e6b8d08b667ce0b747acf66ea97ed21807409002c0df",
          "sha1": "858677dea1fa876e17c4f56f8d2b1c6cde8740ca",
          "md5": "e8c522ef1820c4b06fd57a93927d71cd"
        }
      ]
    }
  ]
}
